/*
 * Decompiled with CFR 0_125.
 * 
 * Could not load the following classes:
 *  com.astryxion.chaospersists.Kyuubi
 *  com.astryxion.chaospersists.ModelKyuubi
 *  net.minecraft.client.renderer.entity.model.Model
 *  net.minecraft.client.renderer.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.math.MathHelper
 *  org.lwjgl.opengl.GL11
 */
package com.astryxion.chaospersists.model;

import com.mojang.blaze3d.vertex.IVertexBuilder;

import com.mojang.blaze3d.matrix.MatrixStack;

import com.astryxion.chaospersists.entity.Kyuubi;
import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;
import org.lwjgl.opengl.GL11;

public class ModelKyuubi extends EntityModel<Kyuubi> {
    private float wingspeed = 1.0f;
    ModelRenderer rtHorn5;
    ModelRenderer lfHorn5;
    ModelRenderer tail9;
    ModelRenderer tail8;
    ModelRenderer tail7;
    ModelRenderer tail6;
    ModelRenderer tail5;
    ModelRenderer tail2;
    ModelRenderer tail1;
    ModelRenderer tail0;
    ModelRenderer lfLegLower;
    ModelRenderer rtLegLower;
    ModelRenderer head;
    ModelRenderer chest;
    ModelRenderer lfArmUpper;
    ModelRenderer rtArmLower;
    ModelRenderer lfLegUpper;
    ModelRenderer rtLegUpper;
    ModelRenderer body;
    ModelRenderer rtArmUpper;
    ModelRenderer lfArmLower;
    ModelRenderer tail3;
    ModelRenderer tail4;
    ModelRenderer lfHorn2;
    ModelRenderer rtHorn1;
    ModelRenderer rtHorn2;
    ModelRenderer lfHorn1;
    ModelRenderer lfHorn3;
    ModelRenderer rtHorn3;
    ModelRenderer lfHorn4;
    ModelRenderer rtHorn4;
    ModelRenderer headFire;
    ModelRenderer lfArmUpperFire;
    ModelRenderer chestFire;
    ModelRenderer bodyFire;
    ModelRenderer lfArmLowerFire;
    ModelRenderer rtArmUpperFire;
    ModelRenderer rtArmLowerFire;
    ModelRenderer lfLegUppperFire;
    ModelRenderer lfLegLowerFire;
    ModelRenderer rtLegUpperFire;
    ModelRenderer rtLegLowerFire;

    public ModelKyuubi(float f1) {
        super(RenderType::entityCutoutNoCull);
        this.wingspeed = f1;
        // textureWidth = 512;
        // textureHeight = 256;
        this.rtHorn5 = new ModelRenderer(this, 56, 8);
        this.rtHorn5.addBox(-0.5f, -0.5f, -2.0f, 1, 1, 2);
        this.rtHorn5.setPos(3.0f, -11.5f, -7.0f);
        this.rtHorn5.mirror = false;
        this.setRotation(this.rtHorn5, -0.4461433f, 0.0f, 0.0f);
        this.lfHorn5 = new ModelRenderer(this, 56, 24);
        this.lfHorn5.addBox(-0.5f, -0.5f, -2.0f, 1, 1, 2);
        this.lfHorn5.setPos(-3.0f, -11.5f, -7.0f);
        this.lfHorn5.mirror = false;
        this.setRotation(this.lfHorn5, -0.4461433f, 0.0f, 0.0f);
        this.tail9 = new ModelRenderer(this, 145, 47);
        this.tail9.addBox(-0.5f, -0.5f, -1.0f, 1, 1, 1);
        this.tail9.setPos(0.0f, 9.0f, -26.0f);
        this.tail9.mirror = false;
        this.setRotation(this.tail9, 2.007645f, 0.0f, 0.0f);
        this.tail8 = new ModelRenderer(this, 135, 45);
        this.tail8.addBox(-1.0f, -1.0f, -2.0f, 2, 2, 2);
        this.tail8.setPos(0.0f, 7.0f, -25.75f);
        this.tail8.mirror = false;
        this.setRotation(this.tail8, 1.524323f, 0.0f, 0.0f);
        this.tail7 = new ModelRenderer(this, 122, 44);
        this.tail7.addBox(-1.5f, -1.5f, -3.0f, 3, 3, 3);
        this.tail7.setPos(0.0f, 5.0f, -24.0f);
        this.tail7.mirror = false;
        this.setRotation(this.tail7, 0.8922867f, 0.0f, 0.0f);
        this.tail6 = new ModelRenderer(this, 105, 43);
        this.tail6.addBox(-2.0f, -2.0f, -4.0f, 4, 4, 4);
        this.tail6.setPos(0.0f, 3.0f, -21.0f);
        this.tail6.mirror = false;
        this.setRotation(this.tail6, 0.6320364f, 0.0f, 0.0f);
        this.tail5 = new ModelRenderer(this, 84, 42);
        this.tail5.addBox(-2.5f, -2.5f, -5.0f, 5, 5, 5);
        this.tail5.setPos(0.0f, 2.0f, -17.0f);
        this.tail5.mirror = false;
        this.setRotation(this.tail5, 0.2230717f, 0.0f, 0.0f);
        this.tail2 = new ModelRenderer(this, 20, 43);
        this.tail2.addBox(-2.0f, -2.0f, -5.0f, 4, 4, 5);
        this.tail2.setPos(0.0f, 10.0f, -7.0f);
        this.tail2.mirror = false;
        this.setRotation(this.tail2, -0.7807508f, 0.0f, 0.0f);
        this.tail1 = new ModelRenderer(this, 9, 36);
        this.tail1.addBox(-1.5f, -1.5f, -3.0f, 3, 3, 3);
        this.tail1.setPos(0.0f, 10.0f, -4.333333f);
        this.tail1.mirror = false;
        this.setRotation(this.tail1, -0.2602503f, 0.0f, 0.0f);
        this.tail0 = new ModelRenderer(this, 0, 46);
        this.tail0.addBox(-1.0f, -1.0f, -3.0f, 4, 4, 3);
        this.tail0.setPos(-1.0f, 9.0f, -2.0f);
        this.tail0.mirror = false;
        this.setRotation(this.tail0, 0.0f, 0.0f, 0.0f);
        this.lfLegLower = new ModelRenderer(this, 205, 55);
        this.lfLegLower.addBox(-2.0f, 0.0f, -3.0f, 4, 6, 4);
        this.lfLegLower.setPos(-3.0f, 18.0f, 2.0f);
        this.lfLegLower.mirror = false;
        this.setRotation(this.lfLegLower, -0.4461433f, 0.0f, 0.0f);
        this.rtLegLower = new ModelRenderer(this, 149, 53);
        this.rtLegLower.addBox(-2.0f, -1.0f, -3.0f, 4, 7, 4);
        this.rtLegLower.setPos(3.0f, 18.0f, 4.0f);
        this.rtLegLower.mirror = false;
        this.setRotation(this.rtLegLower, -0.1487144f, 0.0f, 0.0f);
        this.head = new ModelRenderer(this, 168, 0);
        this.head.addBox(-4.0f, -8.0f, -4.0f, 8, 8, 8);
        this.head.setPos(0.0f, 0.0f, 6.0f);
        this.head.mirror = false;
        this.setRotation(this.head, 0.2230705f, 3.141593f, 0.0f);
        this.chest = new ModelRenderer(this, 170, 17);
        this.chest.addBox(-4.0f, 0.0f, -2.0f, 8, 7, 6);
        this.chest.setPos(0.0f, 0.0f, 5.0f);
        this.chest.mirror = false;
        this.setRotation(this.chest, -0.8551081f, 0.0f, 0.0f);
        this.lfArmUpper = new ModelRenderer(this, 205, 16);
        this.lfArmUpper.addBox(-3.0f, -2.0f, -2.0f, 4, 7, 4);
        this.lfArmUpper.setPos(-5.0f, 2.0f, 3.0f);
        this.lfArmUpper.mirror = false;
        this.setRotation(this.lfArmUpper, 0.0f, 0.0f, 0.3020292f);
        this.rtArmLower = new ModelRenderer(this, 136, 29);
        this.rtArmLower.addBox(-2.0f, 0.0f, -2.0f, 4, 7, 4);
        this.rtArmLower.setPos(7.0f, 6.0f, 2.0f);
        this.rtArmLower.mirror = false;
        this.setRotation(this.rtArmLower, 0.4833219f, 0.0f, 0.0f);
        this.lfLegUpper = new ModelRenderer(this, 188, 46);
        this.lfLegUpper.addBox(-2.0f, 0.0f, -2.0f, 4, 7, 4);
        this.lfLegUpper.setPos(-2.0f, 12.0f, 0.0f);
        this.lfLegUpper.mirror = false;
        this.setRotation(this.lfLegUpper, 0.260246f, 0.0f, 0.2602503f);
        this.rtLegUpper = new ModelRenderer(this, 168, 46);
        this.rtLegUpper.addBox(-2.0f, 0.0f, -2.0f, 4, 7, 4);
        this.rtLegUpper.setPos(2.0f, 12.0f, 0.0f);
        this.rtLegUpper.mirror = false;
        this.setRotation(this.rtLegUpper, 0.5948578f, 0.0f, -0.260246f);
        this.body = new ModelRenderer(this, 170, 31);
        this.body.addBox(-4.0f, 0.0f, -3.0f, 8, 7, 6);
        this.body.setPos(0.0f, 5.0f, 1.0f);
        this.body.mirror = false;
        this.setRotation(this.body, -0.2974289f, 0.0f, 0.0f);
        this.rtArmUpper = new ModelRenderer(this, 142, 16);
        this.rtArmUpper.addBox(-1.0f, -2.0f, -2.0f, 4, 7, 4);
        this.rtArmUpper.setPos(5.0f, 2.0f, 2.0f);
        this.rtArmUpper.mirror = false;
        this.setRotation(this.rtArmUpper, 0.0f, 0.0f, -0.302028f);
        this.lfArmLower = new ModelRenderer(this, 208, 31);
        this.lfArmLower.addBox(-2.0f, 0.0f, -2.0f, 4, 7, 4);
        this.lfArmLower.setPos(-7.0f, 6.0f, 2.0f);
        this.lfArmLower.mirror = false;
        this.setRotation(this.lfArmLower, 0.4833219f, 0.0f, 0.0f);
        this.tail3 = new ModelRenderer(this, 38, 42);
        this.tail3.addBox(-2.5f, -2.0f, -5.0f, 5, 5, 5);
        this.tail3.setPos(0.0f, 6.5f, -10.0f);
        this.tail3.mirror = false;
        this.setRotation(this.tail3, -0.96f, 0.0f, 0.0f);
        this.tail4 = new ModelRenderer(this, 59, 41);
        this.tail4.addBox(-3.0f, -3.0f, -6.0f, 6, 6, 6);
        this.tail4.setPos(0.0f, 3.0f, -12.0f);
        this.tail4.mirror = false;
        this.setRotation(this.tail4, -0.22f, 0.0f, 0.0f);
        this.lfHorn2 = new ModelRenderer(this, 13, 5);
        this.lfHorn2.addBox(-2.0f, -2.0f, -4.0f, 4, 4, 4);
        this.lfHorn2.setPos(-3.0f, -10.0f, 2.0f);
        this.lfHorn2.mirror = false;
        this.setRotation(this.lfHorn2, -0.2230705f, 0.0f, 0.0f);
        this.rtHorn1 = new ModelRenderer(this, 0, 22);
        this.rtHorn1.addBox(-1.5f, -1.5f, -3.0f, 3, 3, 3);
        this.rtHorn1.setPos(3.0f, -8.7f, 4.0f);
        this.rtHorn1.mirror = false;
        this.setRotation(this.rtHorn1, -0.5576792f, 0.0f, 0.0f);
        this.rtHorn2 = new ModelRenderer(this, 13, 21);
        this.rtHorn2.addBox(-2.0f, -2.0f, -4.0f, 4, 4, 4);
        this.rtHorn2.setPos(3.0f, -10.0f, 2.0f);
        this.rtHorn2.mirror = false;
        this.setRotation(this.rtHorn2, -0.2230705f, 0.0f, 0.0f);
        this.lfHorn1 = new ModelRenderer(this, 0, 6);
        this.lfHorn1.addBox(-1.5f, -1.5f, -3.0f, 3, 3, 3);
        this.lfHorn1.setPos(-3.0f, -8.7f, 4.0f);
        this.lfHorn1.mirror = false;
        this.setRotation(this.lfHorn1, -0.5576792f, 0.0f, 0.0f);
        this.lfHorn3 = new ModelRenderer(this, 31, 6);
        this.lfHorn3.addBox(-1.5f, -1.5f, -3.0f, 3, 3, 3);
        this.lfHorn3.setPos(-3.0f, -11.0f, -2.0f);
        this.lfHorn3.mirror = false;
        this.setRotation(this.lfHorn3, -0.0371786f, 0.0f, 0.0f);
        this.rtHorn3 = new ModelRenderer(this, 31, 22);
        this.rtHorn3.addBox(-1.5f, -1.5f, -3.0f, 3, 3, 3);
        this.rtHorn3.setPos(3.0f, -11.0f, -2.0f);
        this.rtHorn3.mirror = false;
        this.setRotation(this.rtHorn3, -0.0371786f, 0.0f, 0.0f);
        this.lfHorn4 = new ModelRenderer(this, 45, 23);
        this.lfHorn4.addBox(-1.0f, -1.0f, -2.0f, 2, 2, 2);
        this.lfHorn4.setPos(-3.0f, -11.0f, -5.0f);
        this.lfHorn4.mirror = false;
        this.setRotation(this.lfHorn4, -0.2230717f, 0.0f, 0.0f);
        this.rtHorn4 = new ModelRenderer(this, 45, 7);
        this.rtHorn4.addBox(-1.0f, -1.0f, -2.0f, 2, 2, 2);
        this.rtHorn4.setPos(3.0f, -11.0f, -5.0f);
        this.rtHorn4.mirror = false;
        this.setRotation(this.rtHorn4, -0.2230717f, 0.0f, 0.0f);
        this.headFire = new ModelRenderer(this, 168, 84);
        this.headFire.addBox(-5.0f, -10.0f, -5.0f, 10, 10, 10);
        this.headFire.setPos(0.0f, 1.0f, 6.0f);
        this.headFire.mirror = false;
        this.setRotation(this.headFire, -0.2230717f, 0.0f, 0.0f);
        this.lfArmUpperFire = new ModelRenderer(this, 209, 108);
        this.lfArmUpperFire.addBox(-6.0f, -1.0f, -3.0f, 6, 9, 6);
        this.lfArmUpperFire.setPos(-3.0f, 1.0f, 3.0f);
        this.lfArmUpperFire.mirror = false;
        this.setRotation(this.lfArmUpperFire, 0.0f, 0.0f, 0.3020292f);
        this.chestFire = new ModelRenderer(this, 170, 105);
        this.chestFire.addBox(-5.0f, 0.0f, -3.0f, 10, 9, 8);
        this.chestFire.setPos(0.0f, -1.0f, 6.0f);
        this.chestFire.mirror = false;
        this.setRotation(this.chestFire, -0.8551081f, 0.0f, 0.0f);
        this.bodyFire = new ModelRenderer(this, 170, 125);
        this.bodyFire.addBox(-5.0f, 0.0f, -4.0f, 10, 9, 8);
        this.bodyFire.setPos(0.0f, 4.0f, 1.0f);
        this.bodyFire.mirror = false;
        this.setRotation(this.bodyFire, -0.2974289f, 0.0f, 0.0f);
        this.lfArmLowerFire = new ModelRenderer(this, 208, 126);
        this.lfArmLowerFire.addBox(-3.0f, 0.0f, -3.0f, 6, 9, 6);
        this.lfArmLowerFire.setPos(-7.333333f, 5.0f, 1.5f);
        this.lfArmLowerFire.mirror = false;
        this.setRotation(this.lfArmLowerFire, 0.4833219f, 0.0f, 0.0f);
        this.rtArmUpperFire = new ModelRenderer(this, 142, 105);
        this.rtArmUpperFire.addBox(-3.0f, 0.0f, -3.0f, 6, 9, 6);
        this.rtArmUpperFire.setPos(5.0f, -1.0f, 2.0f);
        this.rtArmUpperFire.mirror = false;
        this.setRotation(this.rtArmUpperFire, 0.0f, 0.0f, -0.302028f);
        this.rtArmLowerFire = new ModelRenderer(this, 136, 122);
        this.rtArmLowerFire.addBox(-3.0f, 0.0f, -3.0f, 6, 9, 6);
        this.rtArmLowerFire.setPos(7.0f, 5.0f, 1.0f);
        this.rtArmLowerFire.mirror = false;
        this.setRotation(this.rtArmLowerFire, 0.4833219f, 0.0f, 0.0f);
        this.lfLegUppperFire = new ModelRenderer(this, 188, 146);
        this.lfLegUppperFire.addBox(-3.0f, 0.0f, -3.0f, 6, 9, 6);
        this.lfLegUppperFire.setPos(-2.0f, 11.0f, 0.0f);
        this.lfLegUppperFire.mirror = false;
        this.setRotation(this.lfLegUppperFire, 0.260246f, 0.0f, 0.2602503f);
        this.lfLegLowerFire = new ModelRenderer(this, 205, 163);
        this.lfLegLowerFire.addBox(-3.0f, 0.0f, -3.0f, 6, 8, 6);
        this.lfLegLowerFire.setPos(-3.0f, 16.0f, 2.0f);
        this.lfLegLowerFire.mirror = false;
        this.setRotation(this.lfLegLowerFire, -0.4461433f, 0.0f, 0.0f);
        this.rtLegUpperFire = new ModelRenderer(this, 160, 146);
        this.rtLegUpperFire.addBox(-3.0f, 0.0f, -4.0f, 6, 9, 6);
        this.rtLegUpperFire.setPos(2.0f, 11.0f, 0.0f);
        this.rtLegUpperFire.mirror = false;
        this.setRotation(this.rtLegUpperFire, 0.5948578f, 0.0f, -0.260246f);
        this.rtLegLowerFire = new ModelRenderer(this, 150, 167);
        this.rtLegLowerFire.addBox(-3.0f, 0.0f, -3.0f, 6, 9, 6);
        this.rtLegLowerFire.setPos(3.0f, 15.0f, 4.0f);
        this.rtLegLowerFire.mirror = false;
        this.setRotation(this.rtLegLowerFire, -0.1487144f, 0.0f, 0.0f);
    }

    @Override
    public void setupAnim(Kyuubi entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        Kyuubi e = entity;
        float f = limbSwing;
        float f1 = limbSwingAmount;
        float f2 = ageInTicks;
        float f3 = netHeadYaw;
        float f4 = headPitch;
        float f5 = 0.0625F;
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        float newangle = 0.0f;
        newangle = (double)f1 > 0.1 ? MathHelper.cos((float)(f2 * 1.1f * this.wingspeed)) * 3.1415927f * 0.2f * f1 : 0.0f;
        this.rtLegUpper.xRot = 0.59f + newangle;
        this.rtLegUpperFire.xRot = 0.59f + newangle;
        this.rtLegLower.xRot = -0.15f + newangle;
        this.rtLegLowerFire.xRot = -0.15f + newangle;
        this.rtLegLower.z = (float)(Math.sin(this.rtLegUpperFire.xRot) * 8.0);
        this.rtLegLowerFire.z = (float)(Math.sin(this.rtLegUpperFire.xRot) * 8.0);
        this.lfLegUpper.xRot = 0.26f - newangle;
        this.lfLegUppperFire.xRot = 0.26f - newangle;
        this.lfLegLower.xRot = -0.44f - newangle;
        this.lfLegLowerFire.xRot = -0.44f - newangle;
        this.lfLegLower.z = (float)(Math.sin(this.lfLegUppperFire.xRot) * 8.0);
        this.lfLegLowerFire.z = (float)(Math.sin(this.lfLegUppperFire.xRot) * 8.0);
        newangle = MathHelper.cos((float)(f2 * 1.1f * this.wingspeed)) * 3.1415927f * 0.08f * f1;
        this.rtArmUpper.xRot = newangle += MathHelper.cos((float)(f2 * 0.5f * this.wingspeed)) * 3.1415927f * 0.01f;
        this.rtArmUpperFire.xRot = newangle;
        this.rtArmLower.xRot = 0.48f + newangle;
        this.rtArmLowerFire.xRot = 0.48f + newangle;
        this.rtArmLower.z = (float)(Math.sin(this.rtArmUpperFire.xRot) * 8.0);
        this.rtArmLowerFire.z = (float)(Math.sin(this.rtArmUpperFire.xRot) * 8.0);
        this.lfArmUpper.xRot = - newangle;
        this.lfArmUpperFire.xRot = - newangle;
        this.lfArmLower.xRot = 0.48f - newangle;
        this.lfArmLowerFire.xRot = 0.48f - newangle;
        this.lfArmLower.z = (float)(Math.sin(this.lfArmUpperFire.xRot) * 8.0);
        this.lfArmLowerFire.z = (float)(Math.sin(this.lfArmUpperFire.xRot) * 8.0);
        float pi4 = 0.7853975f;
        this.head.yRot = (float)Math.toRadians(f3) + pi4 * 4.0f;
        this.headFire.yRot = (float)Math.toRadians(f3);
        float fc = (float)Math.cos(this.headFire.yRot + pi4);
        float fs = (float)Math.sin(this.headFire.yRot + pi4);
        this.lfHorn1.z = this.headFire.z - fc * 3.6f;
        this.lfHorn1.x = this.headFire.x - fs * 3.6f;
        this.lfHorn1.yRot = this.headFire.yRot + 0.244f + MathHelper.cos((float)(f2 * 1.3f * this.wingspeed)) * 3.1415927f * 0.1f;
        this.lfHorn2.z = this.lfHorn1.z - (float)Math.cos(this.lfHorn1.yRot) * 2.0f;
        this.lfHorn2.x = this.lfHorn1.x - (float)Math.sin(this.lfHorn1.yRot) * 2.0f;
        this.lfHorn2.yRot = this.headFire.yRot + 0.244f + MathHelper.cos((float)(f2 * 1.3f * this.wingspeed - pi4)) * 3.1415927f * 0.1f;
        this.lfHorn3.z = this.lfHorn2.z - (float)Math.cos(this.lfHorn2.yRot) * 4.0f;
        this.lfHorn3.x = this.lfHorn2.x - (float)Math.sin(this.lfHorn2.yRot) * 4.0f;
        this.lfHorn3.yRot = this.headFire.yRot + 0.244f + MathHelper.cos((float)(f2 * 1.3f * this.wingspeed - 2.0f * pi4)) * 3.1415927f * 0.1f;
        this.lfHorn4.z = this.lfHorn3.z - (float)Math.cos(this.lfHorn3.yRot) * 3.0f;
        this.lfHorn4.x = this.lfHorn3.x - (float)Math.sin(this.lfHorn3.yRot) * 3.0f;
        this.lfHorn4.yRot = this.headFire.yRot + 0.244f + MathHelper.cos((float)(f2 * 1.3f * this.wingspeed - 3.0f * pi4)) * 3.1415927f * 0.1f;
        this.lfHorn5.z = this.lfHorn4.z - (float)Math.cos(this.lfHorn4.yRot) * 2.0f;
        this.lfHorn5.x = this.lfHorn4.x - (float)Math.sin(this.lfHorn4.yRot) * 2.0f;
        this.lfHorn5.yRot = this.headFire.yRot + 0.244f + MathHelper.cos((float)(f2 * 1.3f * this.wingspeed - 4.0f * pi4)) * 3.1415927f * 0.1f;
        fc = (float)Math.cos(this.headFire.yRot - pi4);
        fs = (float)Math.sin(this.headFire.yRot - pi4);
        this.rtHorn1.z = this.headFire.z - fc * 3.6f;
        this.rtHorn1.x = this.headFire.x - fs * 3.6f;
        this.rtHorn1.yRot = this.headFire.yRot + -0.244f - MathHelper.cos((float)(f2 * 1.3f * this.wingspeed)) * 3.1415927f * 0.1f;
        this.rtHorn2.z = this.rtHorn1.z - (float)Math.cos(this.rtHorn1.yRot) * 2.0f;
        this.rtHorn2.x = this.rtHorn1.x - (float)Math.sin(this.rtHorn1.yRot) * 2.0f;
        this.rtHorn2.yRot = this.headFire.yRot + -0.244f - MathHelper.cos((float)(f2 * 1.3f * this.wingspeed - pi4)) * 3.1415927f * 0.1f;
        this.rtHorn3.z = this.rtHorn2.z - (float)Math.cos(this.rtHorn2.yRot) * 4.0f;
        this.rtHorn3.x = this.rtHorn2.x - (float)Math.sin(this.rtHorn2.yRot) * 4.0f;
        this.rtHorn3.yRot = this.headFire.yRot + -0.244f - MathHelper.cos((float)(f2 * 1.3f * this.wingspeed - 2.0f * pi4)) * 3.1415927f * 0.1f;
        this.rtHorn4.z = this.rtHorn3.z - (float)Math.cos(this.rtHorn3.yRot) * 3.0f;
        this.rtHorn4.x = this.rtHorn3.x - (float)Math.sin(this.rtHorn3.yRot) * 3.0f;
        this.rtHorn4.yRot = this.headFire.yRot + -0.244f - MathHelper.cos((float)(f2 * 1.3f * this.wingspeed - 3.0f * pi4)) * 3.1415927f * 0.1f;
        this.rtHorn5.z = this.rtHorn4.z - (float)Math.cos(this.rtHorn4.yRot) * 2.0f;
        this.rtHorn5.x = this.rtHorn4.x - (float)Math.sin(this.rtHorn4.yRot) * 2.0f;
        this.rtHorn5.yRot = this.headFire.yRot + -0.244f - MathHelper.cos((float)(f2 * 1.3f * this.wingspeed - 4.0f * pi4)) * 3.1415927f * 0.1f;
        this.tail1.yRot = MathHelper.cos((float)(f2 * 0.9f * this.wingspeed)) * 3.1415927f * 0.2f;
        this.tail2.x = this.tail1.x - (float)Math.sin(this.tail1.yRot) * 3.0f;
        this.tail2.yRot = MathHelper.cos((float)(f2 * 0.9f * this.wingspeed - pi4)) * 3.1415927f * 0.2f;
        this.tail3.x = this.tail2.x - (float)Math.sin(this.tail2.yRot) * 4.0f;
        this.tail3.yRot = MathHelper.cos((float)(f2 * 0.9f * this.wingspeed - 2.0f * pi4)) * 3.1415927f * 0.2f;
        this.tail4.x = this.tail3.x - (float)Math.sin(this.tail3.yRot) * 3.5f;
        this.tail4.yRot = MathHelper.cos((float)(f2 * 0.9f * this.wingspeed - 3.0f * pi4)) * 3.1415927f * 0.2f;
        this.tail5.x = this.tail4.x - (float)Math.sin(this.tail4.yRot) * 5.0f;
        this.tail5.yRot = MathHelper.cos((float)(f2 * 0.9f * this.wingspeed - 4.0f * pi4)) * 3.1415927f * 0.2f;
        this.tail6.x = this.tail5.x - (float)Math.sin(this.tail5.yRot) * 4.0f;
        this.tail6.yRot = MathHelper.cos((float)(f2 * 0.9f * this.wingspeed - 5.0f * pi4)) * 3.1415927f * 0.2f;
        this.tail7.x = this.tail6.x - (float)Math.sin(this.tail6.yRot) * 3.0f;
        this.tail7.yRot = MathHelper.cos((float)(f2 * 0.9f * this.wingspeed - 6.0f * pi4)) * 3.1415927f * 0.2f;
        this.tail8.x = this.tail7.x - (float)Math.sin(this.tail7.yRot) * 2.0f;
        this.tail8.yRot = MathHelper.cos((float)(f2 * 0.9f * this.wingspeed - 7.0f * pi4)) * 3.1415927f * 0.2f;
        this.tail9.x = this.tail8.x - (float)Math.sin(this.tail8.yRot) * 1.0f;
        this.tail9.yRot = MathHelper.cos((float)(f2 * 0.9f * this.wingspeed - 8.0f * pi4)) * 3.1415927f * 0.2f;
        this.tail1.xRot = -0.26f + MathHelper.cos((float)(f2 * 0.5f * this.wingspeed)) * 3.1415927f * 0.1f;
        this.tail2.y = this.tail1.y + (float)Math.sin(this.tail1.xRot) * 3.0f;
        this.tail2.z = this.tail1.z - (float)Math.cos(this.tail1.xRot) * 3.0f;
        this.tail2.xRot = -0.78f + MathHelper.cos((float)(f2 * 0.5f * this.wingspeed - pi4)) * 3.1415927f * 0.1f;
        this.tail3.y = this.tail2.y + (float)Math.sin(this.tail2.xRot) * 4.0f;
        this.tail3.z = this.tail2.z - (float)Math.cos(this.tail2.xRot) * 4.0f;
        this.tail3.xRot = -1.11f + MathHelper.cos((float)(f2 * 0.5f * this.wingspeed - 2.0f * pi4)) * 3.1415927f * 0.1f;
        this.tail4.y = this.tail3.y + (float)Math.sin(this.tail3.xRot) * 3.5f;
        this.tail4.z = this.tail3.z - (float)Math.cos(this.tail3.xRot) * 3.5f;
        this.tail4.xRot = -0.18f + MathHelper.cos((float)(f2 * 0.5f * this.wingspeed - 3.0f * pi4)) * 3.1415927f * 0.1f;
        this.tail5.y = this.tail4.y + (float)Math.sin(this.tail4.xRot) * 5.0f;
        this.tail5.z = this.tail4.z - (float)Math.cos(this.tail4.xRot) * 5.0f;
        this.tail5.xRot = 0.22f + MathHelper.cos((float)(f2 * 0.5f * this.wingspeed - 4.0f * pi4)) * 3.1415927f * 0.1f;
        this.tail6.y = this.tail5.y + (float)Math.sin(this.tail5.xRot) * 4.0f;
        this.tail6.z = this.tail5.z - (float)Math.cos(this.tail5.xRot) * 4.0f;
        this.tail6.xRot = 0.63f + MathHelper.cos((float)(f2 * 0.5f * this.wingspeed - 5.0f * pi4)) * 3.1415927f * 0.1f;
        this.tail7.y = this.tail6.y + (float)Math.sin(this.tail6.xRot) * 3.0f;
        this.tail7.z = this.tail6.z - (float)Math.cos(this.tail6.xRot) * 3.0f;
        this.tail7.xRot = 0.89f + MathHelper.cos((float)(f2 * 0.5f * this.wingspeed - 6.0f * pi4)) * 3.1415927f * 0.1f;
        this.tail8.y = this.tail7.y + (float)Math.sin(this.tail7.xRot) * 2.0f;
        this.tail8.z = this.tail7.z - (float)Math.cos(this.tail7.xRot) * 2.0f;
        this.tail8.xRot = 1.52f + MathHelper.cos((float)(f2 * 0.5f * this.wingspeed - 7.0f * pi4)) * 3.1415927f * 0.1f;
        this.tail9.y = this.tail8.y + (float)Math.sin(this.tail8.xRot) * 2.0f;
        this.tail9.z = this.tail8.z - (float)Math.cos(this.tail8.xRot) * 2.0f;
        this.tail9.xRot = 2.0f + MathHelper.cos((float)(f2 * 0.5f * this.wingspeed - 8.0f * pi4)) * 3.1415927f * 0.1f;    }

    @Override
    public void renderToBuffer(MatrixStack matrixStack, IVertexBuilder buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        matrixStack.pushPose();
                GL11.glEnable((int)2977);
        GL11.glEnable((int)3042);
        GL11.glBlendFunc((int)770, (int)771);
        GL11.glTranslatef((float)0.0f, (float)0.0f, (float)0.0f);
        GL11.glRotatef((float)180.0f, (float)0.0f, (float)1.0f, (float)0.0f);
        GL11.glTranslatef((float)0.0f, (float)0.0f, (float)0.0f);
        this.lfLegLower.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.rtLegLower.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.head.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.chest.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.lfArmUpper.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.rtArmLower.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.lfLegUpper.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.rtLegUpper.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.body.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.rtArmUpper.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.lfArmLower.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.rtHorn5.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.lfHorn5.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.tail9.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.tail8.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.tail7.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.tail6.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.tail5.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.tail2.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.tail1.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.tail0.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.tail3.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.tail4.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.lfHorn2.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.rtHorn1.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.rtHorn2.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.lfHorn1.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.lfHorn3.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.rtHorn3.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.lfHorn4.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.rtHorn4.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.headFire.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.lfArmUpperFire.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.chestFire.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.bodyFire.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.lfArmLowerFire.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.rtArmUpperFire.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.rtArmLowerFire.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.lfLegUppperFire.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.lfLegLowerFire.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.rtLegUpperFire.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        this.rtLegLowerFire.render(matrixStack, buffer, packedLight, packedOverlay, 1.0F, 1.0F, 1.0F, 1.0F);
        GL11.glDisable((int)3042);
                matrixStack.popPose();
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.xRot = x;
        model.yRot = y;
        model.zRot = z;
    }

    public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
        
    }
}

