/*
 * Decompiled with CFR 0_125.
 * 
 * Could not load the following classes:
 *  com.astryxion.chaospersists.ModelStinkBug
 *  net.minecraft.client.renderer.entity.model.Model
 *  net.minecraft.client.renderer.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.math.MathHelper
 */
package com.astryxion.chaospersists.model;

import com.mojang.blaze3d.matrix.MatrixStack;
import com.mojang.blaze3d.vertex.IVertexBuilder;

import com.astryxion.chaospersists.entity.StinkBug;
import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class ModelStinkBug extends EntityModel<StinkBug> {
    private float wingspeed = 1.0f;
    ModelRenderer f6;
    ModelRenderer b10;
    ModelRenderer l6;
    ModelRenderer l4;
    ModelRenderer f4;
    ModelRenderer l5;
    ModelRenderer f5;
    ModelRenderer l3;
    ModelRenderer l2;
    ModelRenderer l1;
    ModelRenderer f3;
    ModelRenderer f2;
    ModelRenderer f1;
    ModelRenderer jaw;
    ModelRenderer b9;
    ModelRenderer head;
    ModelRenderer b4;
    ModelRenderer h1;
    ModelRenderer h2;
    ModelRenderer body;
    ModelRenderer t21;
    ModelRenderer tail;
    ModelRenderer t22;
    ModelRenderer t20;
    ModelRenderer t19;
    ModelRenderer t6;
    ModelRenderer t11;
    ModelRenderer t9;
    ModelRenderer t4;
    ModelRenderer t2;
    ModelRenderer t7;
    ModelRenderer t12;
    ModelRenderer t10;
    ModelRenderer t8;
    ModelRenderer t5;
    ModelRenderer t3;
    ModelRenderer t1;
    ModelRenderer t18;
    ModelRenderer t16;
    ModelRenderer t14;
    ModelRenderer t13;
    ModelRenderer t15;
    ModelRenderer t17;
    ModelRenderer b1;
    ModelRenderer b2;
    ModelRenderer b3;
    ModelRenderer b8;
    ModelRenderer b7;
    ModelRenderer b6;
    ModelRenderer b5;

    public ModelStinkBug(float f1) {
        super(RenderType::entityCutoutNoCull);
        this.wingspeed = f1;
        // textureWidth = 64;
        // textureHeight = 32;
        this.f6 = new ModelRenderer(this, 20, 16);
        this.f6.addBox(-2.0f, 0.0f, -1.0f, 2, 2, 2);
        this.f6.setPos(-3.5f, 16.0f, 3.0f);
        this.f6.mirror = true;
        this.setRotation(this.f6, 0.0f, 0.0f, 0.0f);
        this.b10 = new ModelRenderer(this, 0, 2);
        this.b10.addBox(-0.5f, -1.5f, -0.5f, 1, 2, 1);
        this.b10.setPos(0.0f, 11.0f, 1.0f);
        this.b10.mirror = true;
        this.setRotation(this.b10, -0.5235988f, 0.0f, 0.0f);
        this.l6 = new ModelRenderer(this, 20, 13);
        this.l6.addBox(-2.0f, 0.0f, -1.0f, 2, 1, 2);
        this.l6.setPos(-3.0f, 15.0f, 3.0f);
        this.l6.mirror = true;
        this.setRotation(this.l6, 0.0f, 0.0f, 0.0f);
        this.l4 = new ModelRenderer(this, 20, 13);
        this.l4.addBox(-2.0f, 0.0f, -1.0f, 2, 1, 2);
        this.l4.setPos(-3.0f, 15.0f, -3.0f);
        this.l4.mirror = true;
        this.setRotation(this.l4, 0.0f, 0.0f, 0.0f);
        this.f4 = new ModelRenderer(this, 20, 16);
        this.f4.addBox(-2.0f, 0.0f, -1.0f, 2, 2, 2);
        this.f4.setPos(-3.5f, 16.0f, -3.0f);
        this.f4.mirror = true;
        this.setRotation(this.f4, 0.0f, 0.0f, 0.0f);
        this.l5 = new ModelRenderer(this, 20, 13);
        this.l5.addBox(-2.0f, 0.0f, -1.0f, 2, 1, 2);
        this.l5.setPos(-3.0f, 15.0f, 0.0f);
        this.l5.mirror = true;
        this.setRotation(this.l5, 0.0f, 0.0f, 0.0f);
        this.f5 = new ModelRenderer(this, 20, 16);
        this.f5.addBox(-2.0f, 0.0f, -1.0f, 2, 2, 2);
        this.f5.setPos(-3.5f, 16.0f, 0.0f);
        this.f5.mirror = true;
        this.setRotation(this.f5, 0.0f, 0.0f, 0.0f);
        this.l3 = new ModelRenderer(this, 20, 13);
        this.l3.addBox(0.0f, 0.0f, -1.0f, 2, 1, 2);
        this.l3.setPos(3.0f, 15.0f, 3.0f);
        this.l3.mirror = true;
        this.setRotation(this.l3, 0.0f, 0.0f, 0.0f);
        this.l2 = new ModelRenderer(this, 20, 13);
        this.l2.addBox(0.0f, 0.0f, -1.0f, 2, 1, 2);
        this.l2.setPos(3.0f, 15.0f, 0.0f);
        this.l2.mirror = true;
        this.setRotation(this.l2, 0.0f, 0.0f, 0.0f);
        this.l1 = new ModelRenderer(this, 20, 13);
        this.l1.addBox(0.0f, 0.0f, -1.0f, 2, 1, 2);
        this.l1.setPos(3.0f, 15.0f, -3.0f);
        this.l1.mirror = true;
        this.setRotation(this.l1, 0.0f, 0.0f, 0.0f);
        this.f3 = new ModelRenderer(this, 20, 16);
        this.f3.addBox(0.0f, 0.0f, -1.0f, 2, 2, 2);
        this.f3.setPos(3.5f, 16.0f, 3.0f);
        this.f3.mirror = true;
        this.setRotation(this.f3, 0.0f, 0.0f, 0.0f);
        this.f2 = new ModelRenderer(this, 20, 16);
        this.f2.addBox(0.0f, 0.0f, -1.0f, 2, 2, 2);
        this.f2.setPos(3.5f, 16.0f, 0.0f);
        this.f2.mirror = true;
        this.setRotation(this.f2, 0.0f, 0.0f, 0.0f);
        this.f1 = new ModelRenderer(this, 20, 16);
        this.f1.addBox(0.0f, 0.0f, -1.0f, 2, 2, 2);
        this.f1.setPos(3.5f, 16.0f, -3.0f);
        this.f1.mirror = true;
        this.setRotation(this.f1, 0.0f, 0.0f, 0.0f);
        this.jaw = new ModelRenderer(this, 28, 8);
        this.jaw.addBox(-3.5f, 0.0f, -8.0f, 5, 1, 4);
        this.jaw.setPos(1.0f, 15.0f, 0.0f);
        this.jaw.mirror = true;
        this.setRotation(this.jaw, 0.122173f, 0.0f, 0.0f);
        this.b9 = new ModelRenderer(this, 0, 2);
        this.b9.addBox(-0.5f, -1.5f, -0.5f, 1, 2, 1);
        this.b9.setPos(0.0f, 11.0f, -1.0f);
        this.b9.mirror = true;
        this.setRotation(this.b9, 0.5235988f, 0.0f, 0.0f);
        this.head = new ModelRenderer(this, 28, 0);
        this.head.addBox(-3.5f, -3.5f, -8.0f, 5, 4, 4);
        this.head.setPos(1.0f, 15.0f, 0.0f);
        this.head.mirror = true;
        this.setRotation(this.head, 0.0f, 0.0f, 0.0f);
        this.b4 = new ModelRenderer(this, 0, 0);
        this.b4.addBox(1.0f, -0.5f, 2.5f, 1, 1, 1);
        this.b4.setPos(0.0f, 11.0f, 0.0f);
        this.b4.mirror = true;
        this.setRotation(this.b4, 0.0f, 0.0f, 0.0f);
        this.h1 = new ModelRenderer(this, 0, 2);
        this.h1.addBox(-0.5f, -2.0f, -0.5f, 1, 2, 1);
        this.h1.setPos(-1.5f, 12.0f, -7.0f);
        this.h1.mirror = true;
        this.setRotation(this.h1, 0.5235988f, 0.3490659f, 0.0f);
        this.h2 = new ModelRenderer(this, 0, 2);
        this.h2.addBox(-0.5f, -2.0f, -0.5f, 1, 2, 1);
        this.h2.setPos(1.5f, 12.0f, -7.0f);
        this.h2.mirror = true;
        this.setRotation(this.h2, 0.5235988f, -0.3490659f, 0.0f);
        this.body = new ModelRenderer(this, 0, 0);
        this.body.addBox(-4.0f, -4.0f, -4.0f, 6, 5, 8);
        this.body.setPos(1.0f, 15.0f, 0.0f);
        this.body.mirror = true;
        this.setRotation(this.body, 0.0f, 0.0f, 0.0f);
        this.t21 = new ModelRenderer(this, 0, 0);
        this.t21.addBox(0.5f, 3.5f, 4.0f, 1, 1, 1);
        this.t21.setPos(0.0f, 11.5f, 4.0f);
        this.t21.mirror = true;
        this.setRotation(this.t21, -0.3316126f, 0.0f, 0.0f);
        this.tail = new ModelRenderer(this, 0, 13);
        this.tail.addBox(-2.0f, 0.0f, 0.0f, 4, 4, 6);
        this.tail.setPos(0.0f, 11.5f, 4.0f);
        this.tail.mirror = true;
        this.setRotation(this.tail, -0.3316126f, 0.0f, 0.0f);
        this.t22 = new ModelRenderer(this, 0, 0);
        this.t22.addBox(-1.5f, 3.5f, 4.0f, 1, 1, 1);
        this.t22.setPos(0.0f, 11.5f, 4.0f);
        this.t22.mirror = true;
        this.setRotation(this.t22, -0.3316126f, 0.0f, 0.0f);
        this.t20 = new ModelRenderer(this, 0, 0);
        this.t20.addBox(-1.5f, 3.5f, 2.0f, 1, 1, 1);
        this.t20.setPos(0.0f, 11.5f, 4.0f);
        this.t20.mirror = true;
        this.setRotation(this.t20, -0.3316126f, 0.0f, 0.0f);
        this.t19 = new ModelRenderer(this, 0, 0);
        this.t19.addBox(0.5f, 3.5f, 2.0f, 1, 1, 1);
        this.t19.setPos(0.0f, 11.5f, 4.0f);
        this.t19.mirror = true;
        this.setRotation(this.t19, -0.3316126f, 0.0f, 0.0f);
        this.t6 = new ModelRenderer(this, 0, 0);
        this.t6.addBox(1.5f, 2.5f, 4.0f, 1, 1, 1);
        this.t6.setPos(0.0f, 11.5f, 4.0f);
        this.t6.mirror = true;
        this.setRotation(this.t6, -0.3316126f, 0.0f, 0.0f);
        this.t11 = new ModelRenderer(this, 0, 0);
        this.t11.addBox(0.5f, -0.5f, 4.0f, 1, 1, 1);
        this.t11.setPos(0.0f, 11.5f, 4.0f);
        this.t11.mirror = true;
        this.setRotation(this.t11, -0.3316126f, 0.0f, 0.0f);
        this.t9 = new ModelRenderer(this, 0, 0);
        this.t9.addBox(0.5f, -0.5f, 2.0f, 1, 1, 1);
        this.t9.setPos(0.0f, 11.5f, 4.0f);
        this.t9.mirror = true;
        this.setRotation(this.t9, -0.3316126f, 0.0f, 0.0f);
        this.t4 = new ModelRenderer(this, 0, 0);
        this.t4.addBox(1.5f, 2.5f, 2.0f, 1, 1, 1);
        this.t4.setPos(0.0f, 11.5f, 4.0f);
        this.t4.mirror = true;
        this.setRotation(this.t4, -0.3316126f, 0.0f, 0.0f);
        this.t2 = new ModelRenderer(this, 0, 0);
        this.t2.addBox(1.5f, 2.5f, 0.0f, 1, 1, 1);
        this.t2.setPos(0.0f, 11.5f, 4.0f);
        this.t2.mirror = true;
        this.setRotation(this.t2, -0.3316126f, 0.0f, 0.0f);
        this.t7 = new ModelRenderer(this, 0, 0);
        this.t7.addBox(0.5f, -0.5f, 0.0f, 1, 1, 1);
        this.t7.setPos(0.0f, 11.5f, 4.0f);
        this.t7.mirror = true;
        this.setRotation(this.t7, -0.3316126f, 0.0f, 0.0f);
        this.t12 = new ModelRenderer(this, 0, 0);
        this.t12.addBox(-1.5f, -0.5f, 4.0f, 1, 1, 1);
        this.t12.setPos(0.0f, 11.5f, 4.0f);
        this.t12.mirror = true;
        this.setRotation(this.t12, -0.3316126f, 0.0f, 0.0f);
        this.t10 = new ModelRenderer(this, 0, 0);
        this.t10.addBox(-1.5f, -0.5f, 2.0f, 1, 1, 1);
        this.t10.setPos(0.0f, 11.5f, 4.0f);
        this.t10.mirror = true;
        this.setRotation(this.t10, -0.3316126f, 0.0f, 0.0f);
        this.t8 = new ModelRenderer(this, 0, 0);
        this.t8.addBox(-1.5f, -0.5f, 0.0f, 1, 1, 1);
        this.t8.setPos(0.0f, 11.5f, 4.0f);
        this.t8.mirror = true;
        this.setRotation(this.t8, -0.3316126f, 0.0f, 0.0f);
        this.t5 = new ModelRenderer(this, 0, 0);
        this.t5.addBox(1.5f, 0.5f, 4.0f, 1, 1, 1);
        this.t5.setPos(0.0f, 11.5f, 4.0f);
        this.t5.mirror = true;
        this.setRotation(this.t5, -0.3316126f, 0.0f, 0.0f);
        this.t3 = new ModelRenderer(this, 0, 0);
        this.t3.addBox(1.5f, 0.5f, 2.0f, 1, 1, 1);
        this.t3.setPos(0.0f, 11.5f, 4.0f);
        this.t3.mirror = true;
        this.setRotation(this.t3, -0.3316126f, 0.0f, 0.0f);
        this.t1 = new ModelRenderer(this, 0, 0);
        this.t1.addBox(1.5f, 0.5f, 0.0f, 1, 1, 1);
        this.t1.setPos(0.0f, 11.5f, 4.0f);
        this.t1.mirror = true;
        this.setRotation(this.t1, -0.3316126f, 0.0f, 0.0f);
        this.t18 = new ModelRenderer(this, 0, 0);
        this.t18.addBox(-2.5f, 2.5f, 4.0f, 1, 1, 1);
        this.t18.setPos(0.0f, 11.5f, 4.0f);
        this.t18.mirror = true;
        this.setRotation(this.t18, -0.3316126f, 0.0f, 0.0f);
        this.t16 = new ModelRenderer(this, 0, 0);
        this.t16.addBox(-2.5f, 2.5f, 2.0f, 1, 1, 1);
        this.t16.setPos(0.0f, 11.5f, 4.0f);
        this.t16.mirror = true;
        this.setRotation(this.t16, -0.3316126f, 0.0f, 0.0f);
        this.t14 = new ModelRenderer(this, 0, 0);
        this.t14.addBox(-2.5f, 2.5f, 0.0f, 1, 1, 1);
        this.t14.setPos(0.0f, 11.5f, 4.0f);
        this.t14.mirror = true;
        this.setRotation(this.t14, -0.3316126f, 0.0f, 0.0f);
        this.t13 = new ModelRenderer(this, 0, 0);
        this.t13.addBox(-2.5f, 0.5f, 0.0f, 1, 1, 1);
        this.t13.setPos(0.0f, 11.5f, 4.0f);
        this.t13.mirror = true;
        this.setRotation(this.t13, -0.3316126f, 0.0f, 0.0f);
        this.t15 = new ModelRenderer(this, 0, 0);
        this.t15.addBox(-2.5f, 0.5f, 2.0f, 1, 1, 1);
        this.t15.setPos(0.0f, 11.5f, 4.0f);
        this.t15.mirror = true;
        this.setRotation(this.t15, -0.3316126f, 0.0f, 0.0f);
        this.t17 = new ModelRenderer(this, 0, 0);
        this.t17.addBox(-2.5f, 0.5f, 4.0f, 1, 1, 1);
        this.t17.setPos(0.0f, 11.5f, 4.0f);
        this.t17.mirror = true;
        this.setRotation(this.t17, -0.3316126f, 0.0f, 0.0f);
        this.b1 = new ModelRenderer(this, 0, 0);
        this.b1.addBox(1.0f, -0.5f, -3.5f, 1, 1, 1);
        this.b1.setPos(0.0f, 11.0f, 0.0f);
        this.b1.mirror = true;
        this.setRotation(this.b1, 0.0f, 0.0f, 0.0f);
        this.b2 = new ModelRenderer(this, 0, 0);
        this.b2.addBox(1.5f, -0.5f, -1.5f, 1, 1, 1);
        this.b2.setPos(0.0f, 11.0f, 0.0f);
        this.b2.mirror = true;
        this.setRotation(this.b2, 0.0f, 0.0f, 0.0f);
        this.b3 = new ModelRenderer(this, 0, 0);
        this.b3.addBox(1.5f, -0.5f, 0.5f, 1, 1, 1);
        this.b3.setPos(0.0f, 11.0f, 0.0f);
        this.b3.mirror = true;
        this.setRotation(this.b3, 0.0f, 0.0f, 0.0f);
        this.b8 = new ModelRenderer(this, 0, 0);
        this.b8.addBox(-2.0f, -0.5f, 2.5f, 1, 1, 1);
        this.b8.setPos(0.0f, 11.0f, 0.0f);
        this.b8.mirror = true;
        this.setRotation(this.b8, 0.0f, 0.0f, 0.0f);
        this.b7 = new ModelRenderer(this, 0, 0);
        this.b7.addBox(-2.5f, -0.5f, 0.5f, 1, 1, 1);
        this.b7.setPos(0.0f, 11.0f, 0.0f);
        this.b7.mirror = true;
        this.setRotation(this.b7, 0.0f, 0.0f, 0.0f);
        this.b6 = new ModelRenderer(this, 0, 0);
        this.b6.addBox(-2.5f, -0.5f, -1.5f, 1, 1, 1);
        this.b6.setPos(0.0f, 11.0f, 0.0f);
        this.b6.mirror = true;
        this.setRotation(this.b6, 0.0f, 0.0f, 0.0f);
        this.b5 = new ModelRenderer(this, 0, 0);
        this.b5.addBox(-1.966667f, -0.5f, -3.5f, 1, 1, 1);
        this.b5.setPos(0.0f, 11.0f, 0.0f);
        this.b5.mirror = true;
        this.setRotation(this.b5, 0.0f, 0.0f, 0.0f);
        this.f6.y += 6.0f;
        this.b10.y += 6.0f;
        this.l6.y += 6.0f;
        this.l4.y += 6.0f;
        this.f4.y += 6.0f;
        this.l5.y += 6.0f;
        this.f5.y += 6.0f;
        this.l3.y += 6.0f;
        this.l2.y += 6.0f;
        this.l1.y += 6.0f;
        this.f3.y += 6.0f;
        this.f2.y += 6.0f;
        this.f1.y += 6.0f;
        this.jaw.y += 6.0f;
        this.b9.y += 6.0f;
        this.head.y += 6.0f;
        this.b4.y += 6.0f;
        this.h1.y += 6.0f;
        this.h2.y += 6.0f;
        this.body.y += 6.0f;
        this.t21.y += 6.0f;
        this.tail.y += 6.0f;
        this.t22.y += 6.0f;
        this.t20.y += 6.0f;
        this.t19.y += 6.0f;
        this.t6.y += 6.0f;
        this.t11.y += 6.0f;
        this.t9.y += 6.0f;
        this.t4.y += 6.0f;
        this.t2.y += 6.0f;
        this.t7.y += 6.0f;
        this.t12.y += 6.0f;
        this.t10.y += 6.0f;
        this.t8.y += 6.0f;
        this.t5.y += 6.0f;
        this.t3.y += 6.0f;
        this.t1.y += 6.0f;
        this.t18.y += 6.0f;
        this.t16.y += 6.0f;
        this.t14.y += 6.0f;
        this.t13.y += 6.0f;
        this.t15.y += 6.0f;
        this.t17.y += 6.0f;
        this.b1.y += 6.0f;
        this.b2.y += 6.0f;
        this.b3.y += 6.0f;
        this.b8.y += 6.0f;
        this.b7.y += 6.0f;
        this.b6.y += 6.0f;
        this.b5.y += 6.0f;
    }

    @Override
    public void setupAnim(StinkBug entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        float f = limbSwing;
        float f1 = limbSwingAmount;
        float f2 = ageInTicks;
        float f3 = netHeadYaw;
        float f4 = headPitch;
        float f5 = 0.0625F;
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        float newangle = 0.0f;
        this.f1.xRot = this.f3.xRot = (newangle = MathHelper.sin((float)(f2 * 3.1f * this.wingspeed)) * 3.1415927f * 0.3f * f1);
        this.f4.xRot = this.f6.xRot = - newangle;
        this.f2.xRot = this.f6.xRot;
        this.b9.zRot = newangle = MathHelper.sin((float)(f2 * 0.4f * this.wingspeed)) * 3.1415927f * 0.2f;
        this.b10.zRot = - newangle;
        newangle = MathHelper.sin((float)(f2 * 0.2f * this.wingspeed)) * 3.1415927f * 0.04f;
        this.jaw.xRot = 0.18f + newangle;
        this.h1.xRot = 0.52f + MathHelper.sin((float)(f2 * 0.4f * this.wingspeed)) * 3.1415927f * 0.15f;
        this.h1.yRot = -0.3f + MathHelper.sin((float)(f2 * 0.43f * this.wingspeed)) * 3.1415927f * 0.15f;
        this.h2.xRot = 0.52f + MathHelper.sin((float)(f2 * 0.46f * this.wingspeed)) * 3.1415927f * 0.15f;
        this.h2.yRot = 0.3f + MathHelper.sin((float)(f2 * 0.49f * this.wingspeed)) * 3.1415927f * 0.15f;
        this.t4.xRot = this.t5.xRot = (this.tail.xRot = -0.2f + MathHelper.sin((float)(f2 * 0.1f * this.wingspeed)) * 3.1415927f * 0.1f);
        this.t3.xRot = this.t5.xRot;
        this.t2.xRot = this.t5.xRot;
        this.t1.xRot = this.t5.xRot;
        this.t9.xRot = this.t10.xRot = this.tail.xRot;
        this.t8.xRot = this.t10.xRot;
        this.t7.xRot = this.t10.xRot;
        this.t6.xRot = this.t10.xRot;
        this.t14.xRot = this.t15.xRot = this.tail.xRot;
        this.t13.xRot = this.t15.xRot;
        this.t12.xRot = this.t15.xRot;
        this.t11.xRot = this.t15.xRot;
        this.t19.xRot = this.t20.xRot = this.tail.xRot;
        this.t18.xRot = this.t20.xRot;
        this.t17.xRot = this.t20.xRot;
        this.t16.xRot = this.t20.xRot;
        this.t21.xRot = this.t22.xRot = this.tail.xRot;
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.xRot = x;
        model.yRot = y;
        model.zRot = z;
    }

    public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
        
    }

    @Override
    public void renderToBuffer(MatrixStack matrixStack, IVertexBuilder buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        this.f6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.b10.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.l6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.l4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.f4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.l5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.f5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.l3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.l2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.l1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.f3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.f2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.f1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.b9.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.b4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.h1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.h2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t21.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t22.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t20.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t19.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t11.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t9.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t12.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t10.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t8.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t18.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t16.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t14.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t13.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t15.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.t17.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.b1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.b2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.b3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.b8.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.b7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.b6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.b5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
    }
}
