/*
 * Decompiled with CFR 0_125.
 * 
 * Could not load the following classes:
 *  com.astryxion.chaospersists.ModelThePrinceTeen
 *  com.astryxion.chaospersists.RenderInfo
 *  com.astryxion.chaospersists.ThePrinceTeen
 *  net.minecraft.client.renderer.entity.model.Model
 *  net.minecraft.client.renderer.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.math.MathHelper
 *  org.lwjgl.opengl.GL11
 */
package com.astryxion.chaospersists.model;

import com.mojang.blaze3d.vertex.IVertexBuilder;

import com.mojang.blaze3d.matrix.MatrixStack;

import com.astryxion.chaospersists.render.RenderInfo;
import com.astryxion.chaospersists.entity.ThePrinceTeen;
import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class ModelThePrinceTeen extends EntityModel<ThePrinceTeen> {
    private float wingspeed = 1.0f;
    ModelRenderer body;
    ModelRenderer leftleg1;
    ModelRenderer tail1;
    ModelRenderer leftleg2;
    ModelRenderer body2;
    ModelRenderer leftleg3;
    ModelRenderer tail2;
    ModelRenderer tail3;
    ModelRenderer lclaw2;
    ModelRenderer lclaw4;
    ModelRenderer lclaw5;
    ModelRenderer lclaw6;
    ModelRenderer lclaw7;
    ModelRenderer tail4;
    ModelRenderer tail5;
    ModelRenderer neck1;
    ModelRenderer neck3;
    ModelRenderer head3;
    ModelRenderer jaw1;
    ModelRenderer jaw5;
    ModelRenderer head7;
    ModelRenderer rightleg1;
    ModelRenderer rightleg2;
    ModelRenderer rightleg3;
    ModelRenderer rclaw2;
    ModelRenderer rclaw4;
    ModelRenderer rclaw5;
    ModelRenderer rclaw7;
    ModelRenderer rclaw6;
    ModelRenderer wing1;
    ModelRenderer wing2;
    ModelRenderer mem1;
    ModelRenderer mem2;
    ModelRenderer lshoulder;
    ModelRenderer rshoulder;
    ModelRenderer rwing1;
    ModelRenderer rmem1;
    ModelRenderer rwing2;
    ModelRenderer rmem2;
    ModelRenderer neck4;
    ModelRenderer neck5;
    ModelRenderer wing3;
    ModelRenderer mem3;
    ModelRenderer rwing3;
    ModelRenderer rmem3;
    ModelRenderer wing4;
    ModelRenderer mem4;
    ModelRenderer rwing4;
    ModelRenderer rmem4;
    ModelRenderer Tailspike1;
    ModelRenderer Tailspike2;
    ModelRenderer Tailspike3;
    ModelRenderer headfin;
    ModelRenderer backfin1;
    ModelRenderer backfin2;
    ModelRenderer neck3L;
    ModelRenderer neck4L;
    ModelRenderer neck3R;
    ModelRenderer neck4R;
    ModelRenderer neck5L;
    ModelRenderer neck5R;
    ModelRenderer jaw5L;
    ModelRenderer jaw5R;
    ModelRenderer head7L;
    ModelRenderer headfinL;
    ModelRenderer headfinR;
    ModelRenderer head7R;
    ModelRenderer jaw1L;
    ModelRenderer jaw1R;
    ModelRenderer head3L;
    ModelRenderer head3R;

    public ModelThePrinceTeen(float f1) {
        super(RenderType::entityCutoutNoCull);
        this.wingspeed = f1;
        // textureWidth = 512;
        // textureHeight = 256;
        this.body = new ModelRenderer(this, 400, 26);
        this.body.addBox(-12.5f, -12.0f, -9.0f, 25, 12, 9);
        this.body.setPos(0.0f, 0.0f, 9.0f);
        this.body.mirror = true;
        this.setRotation(this.body, 0.0698132f, 0.0f, 0.0f);
        this.leftleg1 = new ModelRenderer(this, 300, 10);
        this.leftleg1.addBox(-1.0f, -1.0f, -3.0f, 5, 9, 9);
        this.leftleg1.setPos(14.0f, -8.0f, 13.0f);
        this.leftleg1.mirror = true;
        this.setRotation(this.leftleg1, -0.5759587f, 0.0f, 0.0f);
        this.tail1 = new ModelRenderer(this, 400, 82);
        this.tail1.addBox(-9.0f, -6.0f, 0.0f, 18, 10, 12);
        this.tail1.setPos(0.0f, -3.0f, 22.0f);
        this.tail1.mirror = true;
        this.setRotation(this.tail1, -0.1745329f, 0.0f, 0.0f);
        this.leftleg2 = new ModelRenderer(this, 300, 31);
        this.leftleg2.addBox(-1.0f, 6.0f, -7.0f, 4, 12, 5);
        this.leftleg2.setPos(14.0f, -8.0f, 13.0f);
        this.leftleg2.mirror = true;
        this.setRotation(this.leftleg2, 0.9773844f, 0.0f, 0.0f);
        this.body2 = new ModelRenderer(this, 400, 50);
        this.body2.addBox(0.0f, -3.0f, -3.0f, 26, 14, 16);
        this.body2.setPos(-13.0f, -9.0f, 10.0f);
        this.body2.mirror = true;
        this.setRotation(this.body2, -0.1047198f, 0.0f, 0.0f);
        this.leftleg3 = new ModelRenderer(this, 300, 51);
        this.leftleg3.addBox(-1.0f, -1.0f, -2.0f, 3, 19, 4);
        this.leftleg3.setPos(14.0f, 7.0f, 22.0f);
        this.leftleg3.mirror = true;
        this.setRotation(this.leftleg3, -0.5235988f, 0.0f, 0.0f);
        this.tail2 = new ModelRenderer(this, 400, 106);
        this.tail2.addBox(-5.0f, -4.0f, 0.0f, 10, 7, 10);
        this.tail2.setPos(0.0f, -2.0f, 33.0f);
        this.tail2.mirror = true;
        this.setRotation(this.tail2, -0.1396263f, 0.0f, 0.0f);
        this.tail3 = new ModelRenderer(this, 400, 126);
        this.tail3.addBox(-3.0f, -2.0f, 0.0f, 6, 5, 10);
        this.tail3.setPos(0.0f, -2.0f, 42.0f);
        this.tail3.mirror = true;
        this.setRotation(this.tail3, -0.1396263f, 0.0f, 0.0f);
        this.lclaw2 = new ModelRenderer(this, 300, 76);
        this.lclaw2.addBox(-3.0f, 0.0f, -3.0f, 7, 3, 8);
        this.lclaw2.setPos(14.0f, 21.0f, 13.0f);
        this.lclaw2.mirror = true;
        this.setRotation(this.lclaw2, 0.0f, 0.0f, 0.0f);
        this.lclaw4 = new ModelRenderer(this, 310, 123);
        this.lclaw4.addBox(0.0f, 1.0f, -7.0f, 1, 2, 4);
        this.lclaw4.setPos(14.0f, 21.0f, 13.0f);
        this.lclaw4.mirror = true;
        this.setRotation(this.lclaw4, 0.0f, 0.0f, 0.0f);
        this.lclaw5 = new ModelRenderer(this, 297, 123);
        this.lclaw5.addBox(-2.5f, 1.0f, -7.0f, 1, 2, 4);
        this.lclaw5.setPos(14.0f, 21.0f, 13.0f);
        this.lclaw5.mirror = true;
        this.setRotation(this.lclaw5, 0.0f, 0.0f, 0.0f);
        this.lclaw6 = new ModelRenderer(this, 322, 123);
        this.lclaw6.addBox(2.5f, 1.0f, -7.0f, 1, 2, 4);
        this.lclaw6.setPos(14.0f, 21.0f, 13.0f);
        this.lclaw6.mirror = true;
        this.setRotation(this.lclaw6, 0.0f, 0.0f, 0.0f);
        this.lclaw7 = new ModelRenderer(this, 334, 123);
        this.lclaw7.addBox(0.0f, 1.0f, 5.0f, 1, 2, 3);
        this.lclaw7.setPos(14.0f, 21.0f, 13.0f);
        this.lclaw7.mirror = true;
        this.setRotation(this.lclaw7, 0.0f, 0.0f, 0.0f);
        this.tail4 = new ModelRenderer(this, 400, 143);
        this.tail4.addBox(-2.0f, -2.0f, 0.0f, 4, 4, 10);
        this.tail4.setPos(0.0f, 0.0f, 51.0f);
        this.tail4.mirror = true;
        this.setRotation(this.tail4, -0.1396263f, 0.0f, 0.0f);
        this.tail5 = new ModelRenderer(this, 400, 159);
        this.tail5.addBox(-1.5f, -2.0f, 0.0f, 3, 3, 10);
        this.tail5.setPos(0.0f, 2.0f, 59.0f);
        this.tail5.mirror = true;
        this.setRotation(this.tail5, -0.1396263f, 0.0f, 0.0f);
        this.neck1 = new ModelRenderer(this, 400, 7);
        this.neck1.addBox(-12.0f, -4.0f, 0.0f, 24, 8, 8);
        this.neck1.setPos(0.0f, -7.0f, -5.0f);
        this.neck1.mirror = true;
        this.setRotation(this.neck1, 0.0872665f, 0.0f, 0.0f);
        this.neck3 = new ModelRenderer(this, 365, 5);
        this.neck3.addBox(-3.0f, -3.0f, -9.0f, 6, 6, 10);
        this.neck3.setPos(0.0f, -8.0f, -5.0f);
        this.neck3.mirror = true;
        this.setRotation(this.neck3, 0.0174533f, 0.0f, 0.0f);
        this.head3 = new ModelRenderer(this, 143, 149);
        this.head3.addBox(-2.0f, -3.0f, -15.0f, 4, 4, 17);
        this.head3.setPos(0.0f, -6.0f, -34.0f);
        this.head3.mirror = true;
        this.setRotation(this.head3, -0.2443461f, 0.0f, 0.0f);
        this.jaw1 = new ModelRenderer(this, 143, 173);
        this.jaw1.addBox(-1.5f, 1.0f, -14.0f, 3, 2, 12);
        this.jaw1.setPos(0.0f, -6.0f, -34.0f);
        this.jaw1.mirror = true;
        this.setRotation(this.jaw1, 0.1919862f, 0.0f, 0.0f);
        this.jaw5 = new ModelRenderer(this, 144, 206);
        this.jaw5.addBox(-2.5f, 1.0f, -3.0f, 5, 2, 6);
        this.jaw5.setPos(0.0f, -6.0f, -34.0f);
        this.jaw5.mirror = true;
        this.setRotation(this.jaw5, 0.1919862f, 0.0f, 0.0f);
        this.head7 = new ModelRenderer(this, 144, 192);
        this.head7.addBox(-3.0f, -4.0f, -3.0f, 6, 5, 7);
        this.head7.setPos(0.0f, -6.0f, -34.0f);
        this.head7.mirror = true;
        this.setRotation(this.head7, -0.2443461f, 0.0f, 0.0f);
        this.rightleg1 = new ModelRenderer(this, 250, 10);
        this.rightleg1.addBox(-1.0f, -1.0f, -3.0f, 5, 9, 9);
        this.rightleg1.setPos(-17.0f, -8.0f, 13.0f);
        this.rightleg1.mirror = true;
        this.setRotation(this.rightleg1, -0.5934119f, 0.0f, 0.0f);
        this.rightleg2 = new ModelRenderer(this, 250, 32);
        this.rightleg2.addBox(0.0f, 6.0f, -7.0f, 4, 12, 5);
        this.rightleg2.setPos(-17.0f, -8.0f, 13.0f);
        this.rightleg2.mirror = true;
        this.setRotation(this.rightleg2, 0.9773844f, 0.0f, 0.0f);
        this.rightleg3 = new ModelRenderer(this, 250, 52);
        this.rightleg3.addBox(1.0f, 1.0f, -2.0f, 3, 19, 4);
        this.rightleg3.setPos(-17.0f, 5.0f, 23.0f);
        this.rightleg3.mirror = true;
        this.setRotation(this.rightleg3, -0.5235988f, 0.0f, 0.0f);
        this.rclaw2 = new ModelRenderer(this, 250, 76);
        this.rclaw2.addBox(-1.0f, 0.0f, -3.0f, 7, 3, 8);
        this.rclaw2.setPos(-17.0f, 21.0f, 13.0f);
        this.rclaw2.mirror = true;
        this.setRotation(this.rclaw2, 0.0f, 0.0f, 0.0f);
        this.rclaw4 = new ModelRenderer(this, 247, 123);
        this.rclaw4.addBox(2.0f, 1.0f, -7.0f, 1, 2, 4);
        this.rclaw4.setPos(-17.0f, 21.0f, 13.0f);
        this.rclaw4.mirror = true;
        this.setRotation(this.rclaw4, 0.0f, 0.0f, 0.0f);
        this.rclaw5 = new ModelRenderer(this, 258, 123);
        this.rclaw5.addBox(-0.5f, 1.0f, -7.0f, 1, 2, 4);
        this.rclaw5.setPos(-17.0f, 21.0f, 13.0f);
        this.rclaw5.mirror = true;
        this.setRotation(this.rclaw5, 0.0f, 0.0f, 0.0f);
        this.rclaw7 = new ModelRenderer(this, 283, 123);
        this.rclaw7.addBox(2.0f, 1.0f, 5.0f, 1, 2, 3);
        this.rclaw7.setPos(-17.0f, 21.0f, 13.0f);
        this.rclaw7.mirror = true;
        this.setRotation(this.rclaw7, 0.0f, 0.0f, 0.0f);
        this.rclaw6 = new ModelRenderer(this, 270, 123);
        this.rclaw6.addBox(4.5f, 1.0f, -7.0f, 1, 2, 4);
        this.rclaw6.setPos(-17.0f, 21.0f, 13.0f);
        this.rclaw6.mirror = true;
        this.setRotation(this.rclaw6, 0.0f, 0.0f, 0.0f);
        this.wing1 = new ModelRenderer(this, 10, 30);
        this.wing1.addBox(-1.0f, -1.0f, -1.0f, 23, 2, 2);
        this.wing1.setPos(13.0f, -12.0f, 3.0f);
        this.wing1.mirror = true;
        this.setRotation(this.wing1, 0.0f, 0.0872665f, 0.0f);
        this.wing2 = new ModelRenderer(this, 10, 40);
        this.wing2.addBox(-1.0f, -1.0f, -1.0f, 44, 2, 2);
        this.wing2.setPos(34.0f, -12.0f, 1.0f);
        this.wing2.mirror = true;
        this.setRotation(this.wing2, 0.0f, 0.0f, 0.0f);
        this.mem1 = new ModelRenderer(this, 10, 60);
        this.mem1.addBox(-2.0f, 0.0f, 0.0f, 24, 1, 21);
        this.mem1.setPos(13.0f, -12.0f, 3.0f);
        this.mem1.mirror = true;
        this.setRotation(this.mem1, 0.0f, 0.0872665f, 0.0f);
        this.mem2 = new ModelRenderer(this, 10, 85);
        this.mem2.addBox(0.0f, 0.0f, 0.0f, 43, 1, 21);
        this.mem2.setPos(34.0f, -12.0f, 1.0f);
        this.mem2.mirror = true;
        this.setRotation(this.mem2, 0.0f, 0.0f, 0.0f);
        this.lshoulder = new ModelRenderer(this, 370, 78);
        this.lshoulder.addBox(0.0f, 0.0f, 0.0f, 5, 2, 8);
        this.lshoulder.setPos(8.0f, -13.0f, 1.0f);
        this.lshoulder.mirror = true;
        this.setRotation(this.lshoulder, 0.0698132f, 0.0f, 0.0f);
        this.rshoulder = new ModelRenderer(this, 370, 66);
        this.rshoulder.addBox(0.0f, 0.0f, 0.0f, 5, 2, 8);
        this.rshoulder.setPos(-13.0f, -13.0f, 1.0f);
        this.rshoulder.mirror = true;
        this.setRotation(this.rshoulder, 0.0698132f, 0.0f, 0.0f);
        this.rwing1 = new ModelRenderer(this, 10, 140);
        this.rwing1.addBox(-22.0f, -1.0f, -1.0f, 23, 2, 2);
        this.rwing1.setPos(-13.0f, -12.0f, 3.0f);
        this.rwing1.mirror = true;
        this.setRotation(this.rwing1, 0.0f, -0.0872665f, 0.0f);
        this.rmem1 = new ModelRenderer(this, 10, 170);
        this.rmem1.addBox(-22.0f, 0.0f, 0.0f, 24, 1, 21);
        this.rmem1.setPos(-13.0f, -12.0f, 3.0f);
        this.rmem1.mirror = true;
        this.setRotation(this.rmem1, 0.0f, -0.0872665f, 0.0f);
        this.rwing2 = new ModelRenderer(this, 10, 150);
        this.rwing2.addBox(-43.0f, -1.0f, -1.0f, 44, 2, 2);
        this.rwing2.setPos(-34.0f, -12.0f, 1.0f);
        this.rwing2.mirror = true;
        this.setRotation(this.rwing2, 0.0f, 0.0f, 0.0f);
        this.rmem2 = new ModelRenderer(this, 10, 195);
        this.rmem2.addBox(-43.0f, 0.0f, 0.0f, 43, 1, 21);
        this.rmem2.setPos(-34.0f, -12.0f, 1.0f);
        this.rmem2.mirror = true;
        this.setRotation(this.rmem2, 0.0f, 0.0f, 0.0f);
        this.neck4 = new ModelRenderer(this, 366, 23);
        this.neck4.addBox(-2.5f, -2.5f, -9.0f, 5, 5, 10);
        this.neck4.setPos(0.0f, -8.0f, -14.0f);
        this.neck4.mirror = true;
        this.setRotation(this.neck4, 0.1396263f, 0.0f, 0.0f);
        this.neck5 = new ModelRenderer(this, 369, 41);
        this.neck5.addBox(-2.0f, -2.0f, -9.0f, 4, 4, 10);
        this.neck5.setPos(0.0f, -7.0f, -22.0f);
        this.neck5.mirror = true;
        this.setRotation(this.neck5, 0.1396263f, 0.0f, 0.0f);
        this.wing3 = new ModelRenderer(this, 10, 46);
        this.wing3.addBox(0.0f, 0.0f, 0.0f, 44, 2, 2);
        this.wing3.setPos(13.0f, -13.0f, 3.0f);
        this.wing3.mirror = true;
        this.setRotation(this.wing3, 0.0f, 0.0f, -0.3490659f);
        this.mem3 = new ModelRenderer(this, 10, 110);
        this.mem3.addBox(0.0f, 0.0f, 0.0f, 43, 1, 21);
        this.mem3.setPos(13.0f, -12.5f, 5.0f);
        this.mem3.mirror = true;
        this.setRotation(this.mem3, 0.0f, 0.0f, -0.3490659f);
        this.rwing3 = new ModelRenderer(this, 10, 156);
        this.rwing3.addBox(-43.0f, 0.0f, 0.0f, 44, 2, 2);
        this.rwing3.setPos(-13.0f, -13.0f, 3.0f);
        this.rwing3.mirror = true;
        this.setRotation(this.rwing3, 0.0f, 0.0f, 0.3490659f);
        this.rmem3 = new ModelRenderer(this, 10, 221);
        this.rmem3.addBox(-42.0f, 0.0f, 0.0f, 43, 1, 21);
        this.rmem3.setPos(-13.0f, -12.5f, 5.0f);
        this.rmem3.mirror = true;
        this.setRotation(this.rmem3, 0.0f, 0.0f, 0.3490659f);
        this.wing4 = new ModelRenderer(this, 10, 46);
        this.wing4.addBox(0.0f, 0.0f, 0.0f, 44, 2, 2);
        this.wing4.setPos(13.0f, -12.0f, 3.0f);
        this.wing4.mirror = true;
        this.setRotation(this.wing4, 0.0f, 0.0f, 0.3490659f);
        this.mem4 = new ModelRenderer(this, 10, 110);
        this.mem4.addBox(0.0f, 0.0f, 0.0f, 43, 1, 21);
        this.mem4.setPos(13.0f, -11.5f, 5.0f);
        this.mem4.mirror = true;
        this.setRotation(this.mem4, 0.0f, 0.0f, 0.3490659f);
        this.rwing4 = new ModelRenderer(this, 10, 156);
        this.rwing4.addBox(-43.0f, 0.0f, 0.0f, 44, 2, 2);
        this.rwing4.setPos(-13.0f, -12.0f, 3.0f);
        this.rwing4.mirror = true;
        this.setRotation(this.rwing4, 0.0f, 0.0f, -0.3490659f);
        this.rmem4 = new ModelRenderer(this, 10, 221);
        this.rmem4.addBox(-42.0f, 0.0f, 0.0f, 43, 1, 21);
        this.rmem4.setPos(-13.0f, -11.5f, 5.0f);
        this.rmem4.mirror = true;
        this.setRotation(this.rmem4, 0.0f, 0.0f, -0.3490659f);
        this.Tailspike1 = new ModelRenderer(this, 150, 0);
        this.Tailspike1.addBox(-7.0f, 0.0f, 0.0f, 14, 2, 6);
        this.Tailspike1.setPos(0.0f, 2.0f, 69.0f);
        this.Tailspike1.mirror = true;
        this.setRotation(this.Tailspike1, 0.0f, 0.0f, 0.0f);
        this.Tailspike2 = new ModelRenderer(this, 150, 11);
        this.Tailspike2.addBox(-5.0f, 0.0f, 0.0f, 10, 2, 6);
        this.Tailspike2.setPos(0.0f, 2.0f, 75.0f);
        this.Tailspike2.mirror = true;
        this.setRotation(this.Tailspike2, 0.0f, 0.0f, 0.0f);
        this.Tailspike3 = new ModelRenderer(this, 150, 23);
        this.Tailspike3.addBox(0.0f, 0.0f, 0.0f, 1, 1, 15);
        this.Tailspike3.setPos(0.0f, 2.0f, 80.0f);
        this.Tailspike3.mirror = true;
        this.setRotation(this.Tailspike3, 0.0f, 0.0f, 0.0f);
        this.headfin = new ModelRenderer(this, 150, 216);
        this.headfin.addBox(-0.5f, -3.0f, 3.0f, 1, 4, 4);
        this.headfin.setPos(0.0f, -6.0f, -34.0f);
        this.headfin.mirror = true;
        this.setRotation(this.headfin, 0.0872665f, 0.0f, 0.0f);
        this.backfin1 = new ModelRenderer(this, 69, 0);
        this.backfin1.addBox(-0.5f, 0.0f, 0.0f, 1, 6, 6);
        this.backfin1.setPos(0.0f, -11.0f, 0.0f);
        this.backfin1.mirror = true;
        this.setRotation(this.backfin1, 0.7853982f, 0.0f, 0.0f);
        this.backfin2 = new ModelRenderer(this, 85, 0);
        this.backfin2.addBox(-0.5f, 0.0f, 0.0f, 1, 4, 4);
        this.backfin2.setPos(0.0f, -11.0f, 10.0f);
        this.backfin2.mirror = true;
        this.setRotation(this.backfin2, 0.7853982f, 0.0f, 0.0f);
        this.neck3L = new ModelRenderer(this, 365, 100);
        this.neck3L.addBox(-3.0f, -3.0f, -9.0f, 6, 6, 10);
        this.neck3L.setPos(8.0f, -8.0f, -5.0f);
        this.neck3L.mirror = true;
        this.setRotation(this.neck3L, 0.0174533f, 0.0f, 0.0f);
        this.neck4L = new ModelRenderer(this, 366, 119);
        this.neck4L.addBox(-2.5f, -2.5f, -9.0f, 5, 5, 10);
        this.neck4L.setPos(8.0f, -8.0f, -14.0f);
        this.neck4L.mirror = true;
        this.setRotation(this.neck4L, 0.1396263f, 0.0f, 0.0f);
        this.neck3R = new ModelRenderer(this, 365, 175);
        this.neck3R.addBox(-3.0f, -3.0f, -9.0f, 6, 6, 10);
        this.neck3R.setPos(-8.0f, -8.0f, -5.0f);
        this.neck3R.mirror = true;
        this.setRotation(this.neck3R, 0.0174533f, 0.0f, 0.0f);
        this.neck4R = new ModelRenderer(this, 366, 194);
        this.neck4R.addBox(-2.5f, -2.5f, -9.0f, 5, 5, 10);
        this.neck4R.setPos(-8.0f, -8.0f, -14.0f);
        this.neck4R.mirror = true;
        this.setRotation(this.neck4R, 0.1396263f, 0.0f, 0.0f);
        this.neck5L = new ModelRenderer(this, 369, 137);
        this.neck5L.addBox(-2.0f, -2.0f, -9.0f, 4, 4, 10);
        this.neck5L.setPos(8.0f, -7.0f, -23.0f);
        this.neck5L.mirror = true;
        this.setRotation(this.neck5L, 0.1396263f, 0.0f, 0.0f);
        this.neck5R = new ModelRenderer(this, 369, 212);
        this.neck5R.addBox(-2.0f, -2.0f, -9.0f, 4, 4, 10);
        this.neck5R.setPos(-8.0f, -7.0f, -23.0f);
        this.neck5R.mirror = true;
        this.setRotation(this.neck5R, 0.1396263f, 0.0f, 0.0f);
        this.jaw5L = new ModelRenderer(this, 200, 206);
        this.jaw5L.addBox(-2.5f, 1.0f, -3.0f, 5, 2, 6);
        this.jaw5L.setPos(8.0f, -6.0f, -34.0f);
        this.jaw5L.mirror = true;
        this.setRotation(this.jaw5L, 0.1919862f, 0.0f, 0.0f);
        this.jaw5R = new ModelRenderer(this, 250, 206);
        this.jaw5R.addBox(-2.5f, 1.0f, -3.0f, 5, 2, 6);
        this.jaw5R.setPos(-8.0f, -6.0f, -34.0f);
        this.jaw5R.mirror = true;
        this.setRotation(this.jaw5R, 0.1919862f, 0.0f, 0.0f);
        this.head7L = new ModelRenderer(this, 200, 192);
        this.head7L.addBox(-3.0f, -4.0f, -3.0f, 6, 5, 7);
        this.head7L.setPos(8.0f, -6.0f, -34.0f);
        this.head7L.mirror = true;
        this.setRotation(this.head7L, -0.2443461f, 0.0f, 0.0f);
        this.headfinL = new ModelRenderer(this, 200, 216);
        this.headfinL.addBox(-0.5f, -3.0f, 3.0f, 1, 4, 4);
        this.headfinL.setPos(8.0f, -6.0f, -34.0f);
        this.headfinL.mirror = true;
        this.setRotation(this.headfinL, 0.0872665f, 0.0f, 0.0f);
        this.headfinR = new ModelRenderer(this, 250, 216);
        this.headfinR.addBox(-0.5f, -3.0f, 3.0f, 1, 4, 4);
        this.headfinR.setPos(-8.0f, -6.0f, -34.0f);
        this.headfinR.mirror = true;
        this.setRotation(this.headfinR, 0.0872665f, 0.0f, 0.0f);
        this.head7R = new ModelRenderer(this, 250, 192);
        this.head7R.addBox(-3.0f, -4.0f, -3.0f, 6, 5, 7);
        this.head7R.setPos(-8.0f, -6.0f, -34.0f);
        this.head7R.mirror = true;
        this.setRotation(this.head7R, -0.2443461f, 0.0f, 0.0f);
        this.jaw1L = new ModelRenderer(this, 200, 173);
        this.jaw1L.addBox(-1.5f, 1.0f, -14.0f, 3, 2, 12);
        this.jaw1L.setPos(8.0f, -6.0f, -34.0f);
        this.jaw1L.mirror = true;
        this.setRotation(this.jaw1L, 0.1919862f, 0.0f, 0.0f);
        this.jaw1R = new ModelRenderer(this, 250, 173);
        this.jaw1R.addBox(-1.5f, 1.0f, -14.0f, 3, 2, 12);
        this.jaw1R.setPos(-8.0f, -6.0f, -34.0f);
        this.jaw1R.mirror = true;
        this.setRotation(this.jaw1R, 0.1919862f, 0.0f, 0.0f);
        this.head3L = new ModelRenderer(this, 200, 149);
        this.head3L.addBox(-2.0f, -3.0f, -15.0f, 4, 4, 17);
        this.head3L.setPos(8.0f, -6.0f, -34.0f);
        this.head3L.mirror = true;
        this.setRotation(this.head3L, -0.2443461f, 0.0f, 0.0f);
        this.head3R = new ModelRenderer(this, 250, 149);
        this.head3R.addBox(-2.0f, -3.0f, -15.0f, 4, 4, 17);
        this.head3R.setPos(-8.0f, -6.0f, -34.0f);
        this.head3R.mirror = true;
        this.setRotation(this.head3R, -0.2443461f, 0.0f, 0.0f);
    }

    @Override
    public void setupAnim(ThePrinceTeen c, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        float h3;
        float d3;
        RenderInfo r = null;
        float hf = 0.0f;
        float f = limbSwing;
        float f1 = limbSwingAmount;
        float f2 = ageInTicks;
        float f3 = netHeadYaw;
        float f4 = headPitch;
        float f5 = 0.0625F;
        float newangle = 0.0f;
        float newangle2 = 0.0f;
        float rnewangle = 0.0f;
        float rnewangle2 = 0.0f;
        float clawangle = 0.0f;
        float tailspeed = 0.26f;
        float tailamp = 0.08f;
        float pi4 = 0.7853982f;
        int current_activity = c.getActivity();
        boolean useFlightPose = current_activity == 1 && !c.isOnGround();
        this.setRotationAngles(f, f1, f2, f3, f4, f5, c);
        r = c.getRenderInfo();
        newangle = (double)f1 > 0.1 && current_activity == 0 ? MathHelper.cos((float)(f2 * 1.3f * this.wingspeed)) * 3.1415927f * 0.2f * f1 : MathHelper.cos((float)(f2 * 0.3f * this.wingspeed)) * 3.1415927f * 0.04f;
        if (useFlightPose) {
            newangle = MathHelper.cos((float)(f2 * 1.4f * this.wingspeed)) * 3.1415927f * 0.4f;
        }
        if (c.getAttacking() != 0) {
            newangle = MathHelper.cos((float)(f2 * 1.7f * this.wingspeed)) * 3.1415927f * 0.4f;
        }
        if (c.isOnGround() && c.getPassengers().isEmpty() && c.getAttacking() == 0) {
            if ((double)f1 > 0.1) {
                newangle = MathHelper.cos((float)(f2 * 0.35f * this.wingspeed)) * 3.1415927f * 0.05f * f1;
            } else {
                newangle = 0.0f;
            }
        }
        this.wing1.zRot = newangle - 0.4f;
        this.wing2.zRot = newangle * 1.25f - 0.4f;
        this.wing3.zRot = newangle - 0.6f;
        this.wing4.zRot = newangle - 0.2f;
        this.wing2.y = this.wing1.y + (float)Math.sin(this.wing1.zRot) * 22.0f;
        this.wing2.x = this.wing1.x + (float)Math.cos(this.wing1.zRot) * 22.0f;
        this.mem1.zRot = this.wing1.zRot;
        this.mem2.zRot = this.wing2.zRot;
        this.mem3.zRot = this.wing3.zRot;
        this.mem4.zRot = this.wing4.zRot;
        this.mem2.y = this.wing2.y;
        this.mem2.x = this.wing2.x;
        this.rwing1.zRot = - newangle + 0.4f;
        this.rwing2.zRot = (- newangle) * 1.25f + 0.4f;
        this.rwing3.zRot = - newangle + 0.6f;
        this.rwing4.zRot = - newangle + 0.2f;
        this.rwing2.y = this.rwing1.y - (float)Math.sin(this.rwing1.zRot) * 22.0f;
        this.rwing2.x = this.rwing1.x - (float)Math.cos(this.rwing1.zRot) * 22.0f;
        this.rmem1.zRot = this.rwing1.zRot;
        this.rmem2.zRot = this.rwing2.zRot;
        this.rmem3.zRot = this.rwing3.zRot;
        this.rmem4.zRot = this.rwing4.zRot;
        this.rmem2.y = this.rwing2.y;
        this.rmem2.x = this.rwing2.x;
        if ((double)f1 > 0.1) {
            newangle = MathHelper.cos((float)(f2 * 0.55f * this.wingspeed)) * 3.1415927f * 0.25f * f1;
            newangle2 = MathHelper.cos((float)((float)((double)(f2 * 0.55f * this.wingspeed) + 1.5707963267948966))) * 3.1415927f * 0.25f * f1;
            rnewangle = newangle;
            rnewangle2 = newangle2;
            clawangle = 0.0f;
        } else {
            newangle = 0.0f;
            newangle2 = 0.0f;
            rnewangle = 0.0f;
            rnewangle2 = 0.0f;
            clawangle = 0.0f;
        }
        if (c.getAttacking() != 0) {
            newangle = MathHelper.cos((float)(f2 * this.wingspeed)) * 3.1415927f * 0.25f;
            newangle2 = MathHelper.cos((float)((float)((double)(f2 * this.wingspeed) + 1.5707963267948966))) * 3.1415927f * 0.25f;
            rnewangle = newangle;
            rnewangle2 = newangle2;
            clawangle = 0.0f;
        }
        if (useFlightPose && c.getAttacking() == 0) {
            newangle = -0.5f;
            newangle2 = -1.25f;
            rnewangle = 0.5f;
            rnewangle2 = 1.25f;
        }
        if (useFlightPose) {
            clawangle = -0.685f;
        }
        this.leftleg1.xRot = newangle - 0.575f;
        this.leftleg2.xRot = newangle + 0.977f;
        this.leftleg3.xRot = newangle2 - 0.523f;
        this.leftleg3.y = this.leftleg2.y + (float)Math.cos(this.leftleg2.xRot) * 14.0f + 6.0f;
        this.leftleg3.z = this.leftleg2.z + (float)Math.sin(this.leftleg2.xRot) * 14.0f;
        this.lclaw2.y = this.leftleg3.y + (float)Math.cos(this.leftleg3.xRot) * 17.0f;
        this.lclaw2.z = this.leftleg3.z + (float)Math.sin(this.leftleg3.xRot) * 17.0f - 1.0f;
        this.lclaw4.y = this.lclaw2.y;
        this.lclaw4.z = this.lclaw2.z;
        this.lclaw5.y = this.lclaw2.y;
        this.lclaw5.z = this.lclaw2.z;
        this.lclaw6.y = this.lclaw2.y;
        this.lclaw6.z = this.lclaw2.z;
        this.lclaw7.y = this.lclaw2.y;
        this.lclaw7.z = this.lclaw2.z;
        this.lclaw2.xRot = clawangle;
        this.lclaw4.xRot = clawangle;
        this.lclaw5.xRot = clawangle;
        this.lclaw6.xRot = clawangle;
        this.lclaw7.xRot = clawangle;
        this.rightleg1.xRot = - rnewangle - 0.575f;
        this.rightleg2.xRot = - rnewangle + 0.977f;
        this.rightleg3.xRot = - rnewangle2 - 0.523f;
        this.rightleg3.y = this.rightleg2.y + (float)Math.cos(this.rightleg2.xRot) * 14.0f + 5.0f;
        this.rightleg3.z = this.rightleg2.z + (float)Math.sin(this.rightleg2.xRot) * 14.0f;
        this.rclaw2.y = this.rightleg3.y + (float)Math.cos(this.rightleg3.xRot) * 17.0f;
        this.rclaw2.z = this.rightleg3.z + (float)Math.sin(this.rightleg3.xRot) * 17.0f - 1.0f;
        this.rclaw4.y = this.rclaw2.y;
        this.rclaw4.z = this.rclaw2.z;
        this.rclaw5.y = this.rclaw2.y;
        this.rclaw5.z = this.rclaw2.z;
        this.rclaw6.y = this.rclaw2.y;
        this.rclaw6.z = this.rclaw2.z;
        this.rclaw7.y = this.rclaw2.y;
        this.rclaw7.z = this.rclaw2.z;
        this.rclaw2.xRot = clawangle;
        this.rclaw4.xRot = clawangle;
        this.rclaw5.xRot = clawangle;
        this.rclaw6.xRot = clawangle;
        this.rclaw7.xRot = clawangle;
        if (c.getAttacking() != 0) {
            tailspeed = 0.56f;
            tailamp = 0.19f;
        }
        if (c.isOrderedToSit()) {
            tailamp = 0.0f;
        }
        this.tail1.yRot = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed)) * 3.1415927f * tailamp / 4.0f;
        this.tail2.z = this.tail1.z + (float)Math.cos(this.tail1.yRot) * 11.0f;
        this.tail2.x = this.tail1.x + (float)Math.sin(this.tail1.yRot) * 11.0f;
        this.tail2.yRot = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed - pi4)) * 3.1415927f * tailamp;
        this.tail3.z = this.tail2.z + (float)Math.cos(this.tail2.yRot) * 9.0f;
        this.tail3.x = this.tail2.x + (float)Math.sin(this.tail2.yRot) * 9.0f;
        this.tail3.yRot = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed - 2.0f * pi4)) * 3.1415927f * tailamp;
        this.tail4.z = this.tail3.z + (float)Math.cos(this.tail3.yRot) * 9.0f;
        this.tail4.x = this.tail3.x + (float)Math.sin(this.tail3.yRot) * 9.0f;
        this.tail4.yRot = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed - 3.0f * pi4)) * 3.1415927f * tailamp;
        newangle = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed - 3.0f * pi4)) * 3.1415927f * tailamp;
        this.tail5.z = this.tail4.z + (float)Math.cos(this.tail4.yRot) * 9.0f;
        this.tail5.x = this.tail4.x + (float)Math.sin(this.tail4.yRot) * 9.0f;
        this.tail5.yRot = this.tail4.yRot + (newangle /= 2.0f);
        this.Tailspike1.z = this.tail5.z + (float)Math.cos(this.tail5.yRot) * 9.0f;
        this.Tailspike1.x = this.tail5.x + (float)Math.sin(this.tail5.yRot) * 9.0f;
        this.Tailspike2.z = this.tail5.z + (float)Math.cos(this.tail5.yRot) * 15.0f;
        this.Tailspike2.x = this.tail5.x + (float)Math.sin(this.tail5.yRot) * 15.0f;
        this.Tailspike1.yRot = this.Tailspike2.yRot = this.tail5.yRot + newangle * 2.0f / 3.0f;
        this.Tailspike3.z = this.Tailspike1.z + (float)Math.cos(this.Tailspike1.yRot) * 11.0f;
        this.Tailspike3.x = this.Tailspike1.x + (float)Math.sin(this.Tailspike1.yRot) * 11.0f;
        this.Tailspike3.yRot = this.Tailspike1.yRot + newangle * 3.0f / 2.0f;
        if (useFlightPose) {
            f3 = (c.yRotO - c.yRot) * 10.0f;
            f3 = - f3;
            r.rf1 += (f3 - r.rf1) / 50.0f;
            if (r.rf1 > 50.0f) {
                r.rf1 = 50.0f;
            }
            if (r.rf1 < -50.0f) {
                r.rf1 = -50.0f;
            }
            f3 = r.rf1;
        }
        float h2 = h3 = f3 * 2.0f / 3.0f;
        float h1 = h3;
        float d2 = d3 = f4 * 2.0f / 3.0f;
        float d1 = d3;
        if (h1 < 0.0f) {
            h2 = h3 = h1 / 2.0f;
            d2 = d3 = d1 / 2.0f;
        } else {
            h2 = h1 = h3 / 2.0f;
            d2 = d1 = d3 / 2.0f;
        }
        this.head7.yRot = (float)Math.toRadians(h2);
        this.head3.yRot = (float)Math.toRadians(h2);
        this.headfin.yRot = (float)Math.toRadians(h2);
        this.jaw5.yRot = (float)Math.toRadians(h2);
        this.jaw1.yRot = (float)Math.toRadians(h2);
        this.neck3.yRot = (float)Math.toRadians(h2) / 8.0f;
        this.neck4.yRot = (float)Math.toRadians(h2) / 4.0f;
        this.neck5.yRot = (float)Math.toRadians(h2) / 2.0f;
        this.head7L.yRot = (float)Math.toRadians(h1);
        this.head3L.yRot = (float)Math.toRadians(h1);
        this.headfinL.yRot = (float)Math.toRadians(h1);
        this.jaw5L.yRot = (float)Math.toRadians(h1);
        this.jaw1L.yRot = (float)Math.toRadians(h1);
        this.neck3L.yRot = (float)Math.toRadians(h1) / 8.0f;
        this.neck4L.yRot = (float)Math.toRadians(h1) / 4.0f;
        this.neck5L.yRot = (float)Math.toRadians(h1) / 2.0f;
        this.head7R.yRot = (float)Math.toRadians(h3);
        this.head3R.yRot = (float)Math.toRadians(h3);
        this.headfinR.yRot = (float)Math.toRadians(h3);
        this.jaw5R.yRot = (float)Math.toRadians(h3);
        this.jaw1R.yRot = (float)Math.toRadians(h3);
        this.neck3R.yRot = (float)Math.toRadians(h3) / 8.0f;
        this.neck4R.yRot = (float)Math.toRadians(h3) / 4.0f;
        this.neck5R.yRot = (float)Math.toRadians(h3) / 2.0f;
        float Rjx = 0.0f;
        float jx = 0.0f;
        float Ljx = 0.0f;
        if (c.getAttacking() != 0) {
            newangle = MathHelper.cos((float)(f2 * 0.9f * this.wingspeed)) * 3.1415927f * 0.1f;
            Ljx = 0.25f + newangle;
            newangle = MathHelper.cos((float)(f2 * 1.1f * this.wingspeed)) * 3.1415927f * 0.1f;
            Rjx = 0.25f + newangle;
            newangle = MathHelper.cos((float)(f2 * 1.3f * this.wingspeed)) * 3.1415927f * 0.1f;
            jx = 0.25f + newangle;
        } else {
            newangle = MathHelper.cos((float)(f2 * 0.25f * this.wingspeed)) * 3.1415927f * 0.02f;
            Ljx = 0.1f + newangle;
            newangle = MathHelper.cos((float)(f2 * 0.3f * this.wingspeed)) * 3.1415927f * 0.02f;
            Rjx = 0.1f + newangle;
            newangle = MathHelper.cos((float)(f2 * 0.35f * this.wingspeed)) * 3.1415927f * 0.02f;
            jx = 0.1f + newangle;
        }
        this.head7.xRot = (float)Math.toRadians(d2);
        this.head3.xRot = (float)Math.toRadians(d2);
        this.headfin.xRot = (float)Math.toRadians(d2) + 0.5f;
        this.jaw5.xRot = (float)Math.toRadians(d2) + jx;
        this.jaw1.xRot = (float)Math.toRadians(d2) + jx;
        this.head7L.xRot = (float)Math.toRadians(d1);
        this.head3L.xRot = (float)Math.toRadians(d1);
        this.headfinL.xRot = (float)Math.toRadians(d1) + 0.5f;
        this.jaw5L.xRot = (float)Math.toRadians(d1) + Ljx;
        this.jaw1L.xRot = (float)Math.toRadians(d1) + Ljx;
        this.head7R.xRot = (float)Math.toRadians(d3);
        this.head3R.xRot = (float)Math.toRadians(d3);
        this.headfinR.xRot = (float)Math.toRadians(d3) + 0.5f;
        this.jaw5R.xRot = (float)Math.toRadians(d3) + Rjx;
        this.jaw1R.xRot = (float)Math.toRadians(d3) + Rjx;
        d1 = c.getHead1Ext();
        d2 = c.getHead2Ext();
        d3 = c.getHead3Ext();
        this.neck3L.xRot = - (float)Math.toRadians((double)d1 / 3.0);
        this.neck4L.xRot = - (float)Math.toRadians((double)d1 * 2.0 / 3.0);
        this.neck5L.xRot = - (float)Math.toRadians(d1);
        this.neck3.xRot = - (float)Math.toRadians((double)d2 / 3.0);
        this.neck4.xRot = - (float)Math.toRadians((double)d2 * 2.0 / 3.0);
        this.neck5.xRot = - (float)Math.toRadians(d2);
        this.neck3R.xRot = - (float)Math.toRadians((double)d3 / 3.0);
        this.neck4R.xRot = - (float)Math.toRadians((double)d3 * 2.0 / 3.0);
        this.neck5R.xRot = - (float)Math.toRadians(d3);
        this.neck4.y = this.neck3.y + (float)Math.sin(this.neck3.xRot) * 9.0f;
        this.neck4.z = this.neck3.z - (float)Math.cos(this.neck3.xRot) * 9.0f;
        this.neck4.x = this.neck3.x - (float)Math.sin(this.neck3.yRot) * 9.0f * (float)Math.cos(this.neck3.xRot);
        this.neck5.y = this.neck4.y + (float)Math.sin(this.neck4.xRot) * 9.0f;
        this.neck5.z = this.neck4.z - (float)Math.cos(this.neck4.xRot) * 9.0f;
        this.neck5.x = this.neck4.x - (float)Math.sin(this.neck4.yRot) * 9.0f * (float)Math.cos(this.neck4.xRot);
        this.jaw1.y = this.head3.y = (this.head7.y = this.neck5.y + (float)Math.sin(this.neck5.xRot) * 9.0f);
        this.jaw5.y = this.head3.y;
        this.headfin.y = this.head3.y;
        this.jaw1.z = this.head3.z = (this.head7.z = this.neck5.z - (float)Math.cos(this.neck5.xRot) * 9.0f);
        this.jaw5.z = this.head3.z;
        this.headfin.z = this.head3.z;
        this.jaw1.x = this.head3.x = (this.head7.x = this.neck5.x - (float)Math.sin(this.neck5.yRot) * 9.0f * (float)Math.cos(this.neck5.xRot));
        this.jaw5.x = this.head3.x;
        this.headfin.x = this.head3.x;
        this.neck4L.y = this.neck3L.y + (float)Math.sin(this.neck3L.xRot) * 9.0f;
        this.neck4L.z = this.neck3L.z - (float)Math.cos(this.neck3L.xRot) * 9.0f;
        this.neck4L.x = this.neck3L.x - (float)Math.sin(this.neck3L.yRot) * 9.0f * (float)Math.cos(this.neck3L.xRot);
        this.neck5L.y = this.neck4L.y + (float)Math.sin(this.neck4L.xRot) * 9.0f;
        this.neck5L.z = this.neck4L.z - (float)Math.cos(this.neck4L.xRot) * 9.0f;
        this.neck5L.x = this.neck4L.x - (float)Math.sin(this.neck4L.yRot) * 9.0f * (float)Math.cos(this.neck4L.xRot);
        this.jaw1L.y = this.head3L.y = (this.head7L.y = this.neck5L.y + (float)Math.sin(this.neck5L.xRot) * 9.0f);
        this.jaw5L.y = this.head3L.y;
        this.headfinL.y = this.head3L.y;
        this.jaw1L.z = this.head3L.z = (this.head7L.z = this.neck5L.z - (float)Math.cos(this.neck5L.xRot) * 9.0f);
        this.jaw5L.z = this.head3L.z;
        this.headfinL.z = this.head3L.z;
        this.jaw1L.x = this.head3L.x = (this.head7L.x = this.neck5L.x - (float)Math.sin(this.neck5L.yRot) * 9.0f * (float)Math.cos(this.neck5L.xRot));
        this.jaw5L.x = this.head3L.x;
        this.headfinL.x = this.head3L.x;
        this.neck4R.y = this.neck3R.y + (float)Math.sin(this.neck3R.xRot) * 9.0f;
        this.neck4R.z = this.neck3R.z - (float)Math.cos(this.neck3R.xRot) * 9.0f;
        this.neck4R.x = this.neck3R.x - (float)Math.sin(this.neck3R.yRot) * 9.0f * (float)Math.cos(this.neck3R.xRot);
        this.neck5R.y = this.neck4R.y + (float)Math.sin(this.neck4R.xRot) * 9.0f;
        this.neck5R.z = this.neck4R.z - (float)Math.cos(this.neck4R.xRot) * 9.0f;
        this.neck5R.x = this.neck4R.x - (float)Math.sin(this.neck4R.yRot) * 9.0f * (float)Math.cos(this.neck4R.xRot);
        this.jaw1R.y = this.head3R.y = (this.head7R.y = this.neck5R.y + (float)Math.sin(this.neck5R.xRot) * 9.0f);
        this.jaw5R.y = this.head3R.y;
        this.headfinR.y = this.head3R.y;
        this.jaw1R.z = this.head3R.z = (this.head7R.z = this.neck5R.z - (float)Math.cos(this.neck5R.xRot) * 9.0f);
        this.jaw5R.z = this.head3R.z;
        this.headfinR.z = this.head3R.z;
        this.jaw1R.x = this.head3R.x = (this.head7R.x = this.neck5R.x - (float)Math.sin(this.neck5R.yRot) * 9.0f * (float)Math.cos(this.neck5R.xRot));
        this.jaw5R.x = this.head3R.x;
        this.headfinR.x = this.head3R.x;
        c.setRenderInfo(r);
    }

    @Override
    public void renderToBuffer(MatrixStack matrixStack, IVertexBuilder buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        this.body.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftleg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftleg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftleg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightleg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightleg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightleg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lshoulder.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rshoulder.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwing1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwing2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwing3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwing4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tailspike1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tailspike2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tailspike3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headfin.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.backfin1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.backfin2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck3L.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck4L.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck3R.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck4R.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck5L.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck5R.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw5L.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw5R.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head7L.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headfinL.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.headfinR.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head7R.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw1L.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw1R.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head3L.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head3R.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mem1.render(matrixStack, buffer, packedLight, packedOverlay, 0.75F, 0.75F, 0.75F, 0.55F);
        this.mem2.render(matrixStack, buffer, packedLight, packedOverlay, 0.75F, 0.75F, 0.75F, 0.55F);
        this.rmem1.render(matrixStack, buffer, packedLight, packedOverlay, 0.75F, 0.75F, 0.75F, 0.55F);
        this.rmem2.render(matrixStack, buffer, packedLight, packedOverlay, 0.75F, 0.75F, 0.75F, 0.55F);
        this.mem3.render(matrixStack, buffer, packedLight, packedOverlay, 0.75F, 0.75F, 0.75F, 0.55F);
        this.rmem3.render(matrixStack, buffer, packedLight, packedOverlay, 0.75F, 0.75F, 0.75F, 0.55F);
        this.mem4.render(matrixStack, buffer, packedLight, packedOverlay, 0.75F, 0.75F, 0.75F, 0.55F);
        this.rmem4.render(matrixStack, buffer, packedLight, packedOverlay, 0.75F, 0.75F, 0.75F, 0.55F);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.xRot = x;
        model.yRot = y;
        model.zRot = z;
    }

    public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
        
    }
}

