package com.astryxion.chaospersists.core;

import java.util.function.Consumer;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.registries.RegisterEvent;

/**
 * All Chaos Persists / OreSpawn sound events. Mapped from 1.7.10 orespawn sounds.json.
 * Register on the mod bus; entities use these constants instead of registry lookups.
 */
public class ChaosSounds {

    private static final String MODID = "chaospersists";

    public static SoundEvent ALIEN_HURT;
    public static SoundEvent ALIEN_DEATH;
    public static SoundEvent ALIEN_LIVING;
    public static SoundEvent ALO_HURT;
    public static SoundEvent ALO_DEATH;
    public static SoundEvent ALO_LIVING;
    public static SoundEvent B_DARK;
    public static SoundEvent B_DEATH_BOYFRIEND;
    public static SoundEvent B_DEATH_SINGLE;
    public static SoundEvent B_FIGHT;
    public static SoundEvent B_HAPPY;
    public static SoundEvent B_HURT;
    public static SoundEvent B_OW;
    public static SoundEvent B_RAIN;
    public static SoundEvent B_TAUNT;
    public static SoundEvent B_THUNDER;
    public static SoundEvent B_WATER;
    public static SoundEvent B_WOOHOO;
    public static SoundEvent BASILISK_LIVING;
    public static SoundEvent BB_HAPPY;
    public static SoundEvent BEEBUZZ;
    public static SoundEvent BIG_SPLAT;
    public static SoundEvent BIRDS;
    public static SoundEvent CATERKILLER_DEATH;
    public static SoundEvent CATERKILLER_HIT;
    public static SoundEvent CATERKILLER_LIVING;
    public static SoundEvent CHAIN_RATTLES;
    public static SoundEvent CHAINSAW;
    public static SoundEvent CHAINSAWSHORT;
    public static SoundEvent CLATTER;
    public static SoundEvent CLIFFRACER;
    public static SoundEvent CREEPINGHORROR_DEAD;
    public static SoundEvent CREEPINGHORROR_HIT;
    public static SoundEvent CREEPINGHORROR_LIVING;
    public static SoundEvent CRICKET;
    public static SoundEvent CRUNCH;
    public static SoundEvent CRYO_DEATH;
    public static SoundEvent CRYO_HURT;
    public static SoundEvent CRYO_LIVING;
    public static SoundEvent DBDEAD;
    public static SoundEvent DBHIT;
    public static SoundEvent DRAGONFLY_DEATH;
    public static SoundEvent DRAGONFLY_HURT;
    public static SoundEvent DRAGONFLY_LIVING;
    public static SoundEvent DUCK_HURT;
    public static SoundEvent EMPERORSCORPION_DEATH;
    public static SoundEvent FART;
    public static SoundEvent FROG;
    public static SoundEvent GHOST_SOUND;
    public static SoundEvent GLASSDEAD;
    public static SoundEvent GLASSHIT;
    public static SoundEvent GODZILLA_DEATH;
    public static SoundEvent GODZILLA_LIVING;
    public static SoundEvent HAMMERHEAD_DEATH;
    public static SoundEvent HAMMERHEAD_LIVING;
    public static SoundEvent HERCULES_DEATH;
    public static SoundEvent HOVER;
    public static SoundEvent KING_HIT;
    public static SoundEvent KING_LIVING;
    public static SoundEvent KRAKEN_LIVING;
    public static SoundEvent KYUUBI_LIVING;
    public static SoundEvent LEAVES_DEATH;
    public static SoundEvent LEAVES_HIT;
    public static SoundEvent LEON_DEATH;
    public static SoundEvent LEON_HIT;
    public static SoundEvent LEON_LIVING;
    public static SoundEvent LITTLE_SPLAT;
    public static SoundEvent LURKINGHORROR_DEAD;
    public static SoundEvent LURKINGHORROR_HIT;
    public static SoundEvent LURKINGHORROR_LIVING;
    public static SoundEvent MOLENOID_DEATH;
    public static SoundEvent MOLENOID_HIT;
    public static SoundEvent MOLENOID_LIVING;
    public static SoundEvent MOSQUITO;
    public static SoundEvent MOTHRA_WINGS;
    public static SoundEvent O_DARK;
    public static SoundEvent O_DEATH_GIRLFRIEND;
    public static SoundEvent O_DEATH_SINGLE;
    public static SoundEvent O_FIGHT;
    public static SoundEvent O_HAPPY;
    public static SoundEvent O_HURT;
    public static SoundEvent O_OW;
    public static SoundEvent O_RAIN;
    public static SoundEvent O_TAUNT;
    public static SoundEvent O_THUNDER;
    public static SoundEvent O_WATER;
    public static SoundEvent O_WOOHOO;
    public static SoundEvent PEACOCKDEAD;
    public static SoundEvent PEACOCKHIT;
    public static SoundEvent PEACOCKLIVE;
    public static SoundEvent PITCHBLACK_DEAD;
    public static SoundEvent PITCHBLACK_HIT;
    public static SoundEvent PITCHBLACK_LIVING;
    public static SoundEvent RATDEAD;
    public static SoundEvent RATHIT;
    public static SoundEvent RATLIVE;
    public static SoundEvent ROAR;
    public static SoundEvent ROBOT_DEATH;
    public static SoundEvent ROBOT_HURT;
    public static SoundEvent ROBOT_LIVING;
    public static SoundEvent ROBOT1_DEATH;
    public static SoundEvent ROBOTSPIDER;
    public static SoundEvent ROBOTSPIDERMOUNT;
    public static SoundEvent RUBYBIRD;
    public static SoundEvent SCORPION_ATTACK;
    public static SoundEvent SCORPION_HIT;
    public static SoundEvent SCORPION_LIVING;
    public static SoundEvent SEAMONSTER_DEATH;
    public static SoundEvent SEAMONSTER_HIT;
    public static SoundEvent SEAMONSTER_LIVING;
    public static SoundEvent SEAVIPER_DEATH;
    public static SoundEvent SEAVIPER_HIT;
    public static SoundEvent SEAVIPER_LIVING;
    public static SoundEvent SQUID_DEATH;
    public static SoundEvent SQUID_HURT;
    public static SoundEvent TERRIBLETERROR_DEAD;
    public static SoundEvent TERRIBLETERROR_HIT;
    public static SoundEvent TERRIBLETERROR_LIVING;
    public static SoundEvent TREX_DEATH;
    public static SoundEvent TREX_LIVING;
    public static SoundEvent TRIFFID_DEAD;
    public static SoundEvent TRIFFID_HIT;
    public static SoundEvent TRIFFID_LIVING;
    public static SoundEvent VORTEXLIVE;
    public static SoundEvent WATERDRAGON_DEATH;
    public static SoundEvent WATERDRAGON_HURT;
    public static SoundEvent WTF_HURT;
    public static SoundEvent WTF_LIVING;

    private static SoundEvent create(String name) {
        ResourceLocation loc = new ResourceLocation(MODID, name);
        return SoundEvent.createVariableRangeEvent(loc);
    }

    private static void register(RegisterEvent event, String name, Consumer<SoundEvent> assign) {
        ResourceLocation loc = new ResourceLocation(MODID, name);
        SoundEvent sound = SoundEvent.createVariableRangeEvent(loc);
        assign.accept(sound);
        event.register(net.minecraft.core.registries.Registries.SOUND_EVENT, loc, () -> sound);
    }

    /** Call from RegistrySoundHandler on RegisterEvent for SoundEvent. */
    public static void registerSounds(RegisterEvent event) {
        register(event, "alien_hurt", s -> ALIEN_HURT = s);
        register(event, "alien_death", s -> ALIEN_DEATH = s);
        register(event, "alien_living", s -> ALIEN_LIVING = s);
        register(event, "alo_hurt", s -> ALO_HURT = s);
        register(event, "alo_death", s -> ALO_DEATH = s);
        register(event, "alo_living", s -> ALO_LIVING = s);
        register(event, "b_dark", s -> B_DARK = s);
        register(event, "b_death_boyfriend", s -> B_DEATH_BOYFRIEND = s);
        register(event, "b_death_single", s -> B_DEATH_SINGLE = s);
        register(event, "b_fight", s -> B_FIGHT = s);
        register(event, "b_happy", s -> B_HAPPY = s);
        register(event, "b_hurt", s -> B_HURT = s);
        register(event, "b_ow", s -> B_OW = s);
        register(event, "b_rain", s -> B_RAIN = s);
        register(event, "b_taunt", s -> B_TAUNT = s);
        register(event, "b_thunder", s -> B_THUNDER = s);
        register(event, "b_water", s -> B_WATER = s);
        register(event, "b_woohoo", s -> B_WOOHOO = s);
        register(event, "basilisk_living", s -> BASILISK_LIVING = s);
        register(event, "bb_happy", s -> BB_HAPPY = s);
        register(event, "beebuzz", s -> BEEBUZZ = s);
        register(event, "big_splat", s -> BIG_SPLAT = s);
        register(event, "birds", s -> BIRDS = s);
        register(event, "caterkiller_death", s -> CATERKILLER_DEATH = s);
        register(event, "caterkiller_hit", s -> CATERKILLER_HIT = s);
        register(event, "caterkiller_living", s -> CATERKILLER_LIVING = s);
        register(event, "chain_rattles", s -> CHAIN_RATTLES = s);
        register(event, "chainsaw", s -> CHAINSAW = s);
        register(event, "chainsawshort", s -> CHAINSAWSHORT = s);
        register(event, "clatter", s -> CLATTER = s);
        register(event, "cliffracer", s -> CLIFFRACER = s);
        register(event, "creepinghorror_dead", s -> CREEPINGHORROR_DEAD = s);
        register(event, "creepinghorror_hit", s -> CREEPINGHORROR_HIT = s);
        register(event, "creepinghorror_living", s -> CREEPINGHORROR_LIVING = s);
        register(event, "cricket", s -> CRICKET = s);
        register(event, "crunch", s -> CRUNCH = s);
        register(event, "cryo_death", s -> CRYO_DEATH = s);
        register(event, "cryo_hurt", s -> CRYO_HURT = s);
        register(event, "cryo_living", s -> CRYO_LIVING = s);
        register(event, "dbdead", s -> DBDEAD = s);
        register(event, "dbhit", s -> DBHIT = s);
        register(event, "dragonfly_death", s -> DRAGONFLY_DEATH = s);
        register(event, "dragonfly_hurt", s -> DRAGONFLY_HURT = s);
        register(event, "dragonfly_living", s -> DRAGONFLY_LIVING = s);
        register(event, "duck_hurt", s -> DUCK_HURT = s);
        register(event, "emperorscorpion_death", s -> EMPERORSCORPION_DEATH = s);
        register(event, "fart", s -> FART = s);
        register(event, "frog", s -> FROG = s);
        register(event, "ghost_sound", s -> GHOST_SOUND = s);
        register(event, "glassdead", s -> GLASSDEAD = s);
        register(event, "glasshit", s -> GLASSHIT = s);
        register(event, "godzilla_death", s -> GODZILLA_DEATH = s);
        register(event, "godzilla_living", s -> GODZILLA_LIVING = s);
        register(event, "hammerhead_death", s -> HAMMERHEAD_DEATH = s);
        register(event, "hammerhead_living", s -> HAMMERHEAD_LIVING = s);
        register(event, "hercules_death", s -> HERCULES_DEATH = s);
        register(event, "hover", s -> HOVER = s);
        register(event, "king_hit", s -> KING_HIT = s);
        register(event, "king_living", s -> KING_LIVING = s);
        register(event, "kraken_living", s -> KRAKEN_LIVING = s);
        register(event, "kyuubi_living", s -> KYUUBI_LIVING = s);
        register(event, "leaves_death", s -> LEAVES_DEATH = s);
        register(event, "leaves_hit", s -> LEAVES_HIT = s);
        register(event, "leon_death", s -> LEON_DEATH = s);
        register(event, "leon_hit", s -> LEON_HIT = s);
        register(event, "leon_living", s -> LEON_LIVING = s);
        register(event, "little_splat", s -> LITTLE_SPLAT = s);
        register(event, "lurkinghorror_dead", s -> LURKINGHORROR_DEAD = s);
        register(event, "lurkinghorror_hit", s -> LURKINGHORROR_HIT = s);
        register(event, "lurkinghorror_living", s -> LURKINGHORROR_LIVING = s);
        register(event, "molenoid_death", s -> MOLENOID_DEATH = s);
        register(event, "molenoid_hit", s -> MOLENOID_HIT = s);
        register(event, "molenoid_living", s -> MOLENOID_LIVING = s);
        register(event, "mosquito", s -> MOSQUITO = s);
        register(event, "mothrawings", s -> MOTHRA_WINGS = s);
        register(event, "o_dark", s -> O_DARK = s);
        register(event, "o_death_girlfriend", s -> O_DEATH_GIRLFRIEND = s);
        register(event, "o_death_single", s -> O_DEATH_SINGLE = s);
        register(event, "o_fight", s -> O_FIGHT = s);
        register(event, "o_happy", s -> O_HAPPY = s);
        register(event, "o_hurt", s -> O_HURT = s);
        register(event, "o_ow", s -> O_OW = s);
        register(event, "o_rain", s -> O_RAIN = s);
        register(event, "o_taunt", s -> O_TAUNT = s);
        register(event, "o_thunder", s -> O_THUNDER = s);
        register(event, "o_water", s -> O_WATER = s);
        register(event, "o_woohoo", s -> O_WOOHOO = s);
        register(event, "peacockdead", s -> PEACOCKDEAD = s);
        register(event, "peacockhit", s -> PEACOCKHIT = s);
        register(event, "peacocklive", s -> PEACOCKLIVE = s);
        register(event, "pitchblack_dead", s -> PITCHBLACK_DEAD = s);
        register(event, "pitchblack_hit", s -> PITCHBLACK_HIT = s);
        register(event, "pitchblack_living", s -> PITCHBLACK_LIVING = s);
        register(event, "ratdead", s -> RATDEAD = s);
        register(event, "rathit", s -> RATHIT = s);
        register(event, "ratlive", s -> RATLIVE = s);
        register(event, "roar", s -> ROAR = s);
        register(event, "robot_death", s -> ROBOT_DEATH = s);
        register(event, "robot_hurt", s -> ROBOT_HURT = s);
        register(event, "robot_living", s -> ROBOT_LIVING = s);
        register(event, "robot1_death", s -> ROBOT1_DEATH = s);
        register(event, "robotspider", s -> ROBOTSPIDER = s);
        register(event, "robotspidermount", s -> ROBOTSPIDERMOUNT = s);
        register(event, "rubybird", s -> RUBYBIRD = s);
        register(event, "scorpion_attack", s -> SCORPION_ATTACK = s);
        register(event, "scorpion_hit", s -> SCORPION_HIT = s);
        register(event, "scorpion_living", s -> SCORPION_LIVING = s);
        register(event, "seamonster_death", s -> SEAMONSTER_DEATH = s);
        register(event, "seamonster_hit", s -> SEAMONSTER_HIT = s);
        register(event, "seamonster_living", s -> SEAMONSTER_LIVING = s);
        register(event, "seaviper_death", s -> SEAVIPER_DEATH = s);
        register(event, "seaviper_hit", s -> SEAVIPER_HIT = s);
        register(event, "seaviper_living", s -> SEAVIPER_LIVING = s);
        register(event, "squid_death", s -> SQUID_DEATH = s);
        register(event, "squid_hurt", s -> SQUID_HURT = s);
        register(event, "terribleterror_dead", s -> TERRIBLETERROR_DEAD = s);
        register(event, "terribleterror_hit", s -> TERRIBLETERROR_HIT = s);
        register(event, "terribleterror_living", s -> TERRIBLETERROR_LIVING = s);
        register(event, "trex_death", s -> TREX_DEATH = s);
        register(event, "trex_living", s -> TREX_LIVING = s);
        register(event, "triffid_dead", s -> TRIFFID_DEAD = s);
        register(event, "triffid_hit", s -> TRIFFID_HIT = s);
        register(event, "triffid_living", s -> TRIFFID_LIVING = s);
        register(event, "vortexlive", s -> VORTEXLIVE = s);
        register(event, "waterdragon_death", s -> WATERDRAGON_DEATH = s);
        register(event, "waterdragon_hurt", s -> WATERDRAGON_HURT = s);
        register(event, "wtf_hurt", s -> WTF_HURT = s);
        register(event, "wtf_living", s -> WTF_LIVING = s);
    }
}
